- src/components/Clusters.tsx
In React, it's a good practice to explicitly check for **null** or **undefined** before trying to access properties like length or calling .map() on arrays.
fixes #12
> fix: added logic to check for undefined length in Cluster.txt

- README.md
It's better to keep it like that because I simply copied the command from the README.md file. Then, when I was about to raise a new PR, I found that I had the wrong remote origin, and later discovered this note in the README.md file:
> fix: replace katamyra with your-github-username

- .github/workflows/greeting.yml
Why this is helpful ?
I have seen a lot of new contributors raise new issues or PRs and then seek help without even reading the CONTRIBUTING.md file. They also struggle to find the community channel to get help for their PR or issue.
One more point, https://github.com/kubestellar/kubestellar already uses a greeting GitHub Action.  I thought it would be a great idea to implement something similar in this repository as well.
> feat: added greeting message for new contributor

- .dockerignore
- backend/.dockerignore
- backend/Dockerfile
- docker-compose.yml
Reduce binary size of the Go application by optimizing the Dockerfile and include .dockerignore files to prevent unnecessary files from being included in the Docker context.
@clubanderson review my PR
> Optimize Dockerfile and add .dockerignore files

- .github/workflows/ci.yml
Modify the CI workflow to trigger on all branches instead of just the main branch.
> chore(ci): update branch filter to allow all branches for CI workflow

- src/components/Header.tsx
Adjust the logo image styling to ensure better responsiveness by changing the height to auto and using the object-contain property.
Fixes #70
> Fix logo image styling for better responsiveness in Header

- src/pages/ITS.tsx
The search functionality in the "Managed Clusters" section of the application was not working correctly. While the search query was being captured, the displayed clusters were not being filtered accordingly. This PR fixes that issue by ensuring the clusters are filtered based on the search input.
Fixes #84 
- Added a filteredClusters variable to filter clusters based on the search query and status filter.
- Updated the table to map over currentClusters instead of clusters to reflect the filtered results.
- Updated pagination to use filteredClusters.length for calculating total pages.
- Implemented case-insensitive search that matches clusters containing the search query.
- Ensured pagination resets to the first page when the search query changes for a better user experience.
Please ensure …
> Fix: Implement Search Functionality for Cluster Names

- src/pages/ITS.tsx
The buttons on the "Managed Clusters" page were not properly aligned with the search bar and dropdown menu, leading to UI inconsistency and usability issues. This PR ensures proper horizontal alignment of all elements.
Fixes #91 
- Removed the mb-4 class from individual input and select containers.
- Added a border to the Import Cluster button for visual consistency.
- Kept mb-4 only on the parent container to maintain proper spacing.
> fix: Align buttons, search bar, and dropdown in Managed Clusters page

- package-lock.json
- package.json
- src/components/CreateOptions.tsx
- src/components/DeploymentTable.tsx
- src/components/PieChartDisplay.tsx
- src/pages/WDS.tsx
This PR introduces a new Create Workload feature in WDS, allowing users to apply workloads using three methods , Workload Status , Deployment Staus Tabel:
Write YAML/JSON manually.
Upload a file from their PC.
Use a form to create workloads interactively.
Additionally, it includes features for:
Workload status tracking
Viewing running deployments, services, etc.
A Deployment Table to display all deployment data.
Partially addresses #51  
Implement a WDS frontend supported by WDS backend endpoints.
Changes Made
Added Create Workload feature with three input methods.
Implemented Workload Status tracking.
Created a Deployment Table to display deployment data.
Improved UI/UX for workload management.
Checklist
✅ I have reviewed the project's contribution guidelines.
✅ I have tested the changes …
> Added new components and modified WDS page

- src/App.tsx
- src/components/Header.tsx
- src/components/menu/MenuItem.tsx
- src/context/ClusterContext.tsx
This PR introduces a global cluster selection state and updates the application to disable menu items when no cluster is selected. This ensures a better user experience by preventing navigation to other menu Items.
Fixes #96 
- Created a Cluster Context: Manages cluster selection state across the app.
- Updated the Header Component:
- Disables menu items when no cluster is selected. Keeps "Home," "User," and "Onboard" always enabled.
- Disabled menu items are grayed out with reduced opacity.
- Included the ClusterProvider to manage global state.
> Disable menu items when no cluster is selected & add visual feedback

- src/pages/NotFoundPage.tsx
The logo on the 404 page was overflowing the content due to an incorrect z-index value, causing it to extend beyond its intended boundary and overlap with other elements.
Fixes #106 
- Updated the tailwind class for the logo component to set a corrected z-index value.
> Fixed the logo overflow on Not Found Page(404( Page

- backend/main.go
- src/components/Header.tsx
- src/components/menu/MenuItem.tsx
This pull request addresses the issue of cluster selection in the header dropdown of the application. The changes ensure that only valid kubeflex contexts are displayed and selected correctly. Additionally, the menu items are now properly disabled based on the availability of clusters.
Fixes #116 
- Use the its1 context to fetch the managed clusters list
- Return both the kubeflex contexts and the managed clusters from its1
> Fix#116 cluster selection

- backend/main.go
- backend/wds/common.go
- backend/wds/deployment/common.go
- backend/wds/deployment/details.go
- backend/wds/deployment/logs.go
- backend/wds/deployment/status.go
- backend/wds/resources/services.go
Fixes #100 
- GetServiceList :  /api/services/:namespace
- GetServiceByServiceName: /api/services/:namespace/:name
- added create resource service route : /api/services/create
- Delete service - /api/services/delete
And also moved the GetClientSetKubeConfig from /wds/deployment/common.go to /wds/common.go 
```bash
{
"name": "my-service",
"namespace": "default",
"labels": {
"app": "my-app",
"env": "production"
},
"ports": [
{
"name": "http",
"port": 80,
"targetPort": 8080,
"protocol": "TCP"
},
{
"name": "https",
"port": 443,
"targetPort": 8443,
"protocol": "TCP"
},
{
"name": "custom-port",
"port": 9090,
"targetPort": 9091,
"protocol": "UDP"
}
]
}
```
> feat: WDS backend Implementation for Kubernetes Service Resources

- .gitignore
- backend/main.go
- backend/wds/deployment/common.go
Fixes #127
https://github.com/user-attachments/assets/07e73099-c785-44de-8486-954be3329376
Sample Data - 
```json
{
"name": "user-demo-nginx",
"namespace": "default",
"replicas": 2,
"labels": {
"app": "nginx"
},
"container": {
"name":"nginx",
"image":"nnginx:latest",
"ports": [{
"ContainerPort":80
}]
}
}
```
Note: 
- Creating the deployment from local file or github URL and path - Use this route - `http://localhost:4000/api/wds/create`
- Creating the deployment from user configuration data - use this route - `http://localhost:4000/api/wds/create/json`
> feat: added new route to handle user raw deployment configuration data to create deployment workload 

- src/components/CreateBindingPolicyDialog.tsx
Add a default YAML template for KubeStellar Binding Policies in the CreateBindingPolicyDialog component. This template provides users with a clear starting point for creating and configuring their binding policies.
Fixes #159 
- Created the defaultYamlTemplate in the CreateBindingPolicyDialog component.
- Ensure that the template is displayed when the dialog is opened for creating a new Binding Policy.
- Test the dialog to confirm that the template loads correctly and is editable by the user.
- Added a cancel alert dialog in the CreateBindingPolicyDialog component.
> Added a binding policy tempelate while creating a new policy

- src/components/ClustersTable.tsx
Fix Filter Functionality in ClustersTable
Fixes #93
- Tested search with various cluster names and labels
- Verified filter works for different status values
- Confirmed combined search and filter functionality
- Tested empty state handling
https://github.com/user-attachments/assets/f8f7bddd-4a60-4f28-82cc-78f2b7a30034
> fix: Improve search and filter functionality in ClustersTable

- src/components/BindingPolicy/BPPagination.tsx
- src/components/BindingPolicy/BPTable.tsx
- src/components/BindingPolicy/Dialogs/BPHeader.tsx
- src/components/BindingPolicy/Dialogs/DeleteDialog.tsx
- src/components/BindingPolicy/PreviewDialog.tsx
- src/pages/BP.tsx
- src/types/bindingPolicy.ts
This PR restructures the codebase by separating concerns into individual components (BPHeader, BPTable, BPPagination, DeleteDialog), improving maintainability,  and reusability. Centralized types enhance type consistency, while reducing complexity and making the overall structure easier to understand.
Partially addresses: #54 
- Simplifies the overall structure and reduces complexity of the main BP component.
- Assigns specific responsibilities to components:
1.     - BPHeader: Manages search and action buttons.
2.     - BPTable: Displays binding policies data.
3.     - BPPagination: Handles pagination UI.
4.     - DeleteDialog: Manages policy deletion confirmation.
- Centralizes types in a separate file for consistent type management.
- Adds status filtering (Active/Inactive) with visual …
> Refactored and moved the BP component into small components

- src/components/ClustersTable.tsx
- src/components/ImportClusters.tsx
- src/components/menu/data.ts
Created a pop-up table `ImportClusters.tsx` to import clusters that opens on the Import Cluster button when clicked. I used the `CreateOptions.tsx` file as a base for the pop-up table. I tailored it as much as I can while keeping the table working.
Still need to fix up the tabs. Rename the Yaml paste tab to a relevant import option. Add in API/URL textbox and form for manual import. Need to check if the upload file is working on Kubeconfig. And keep tailoring this table.
> Created Import pop-up table and opens on Import Cluster button

- src/components/BindingPolicy/BPPagination.tsx
- src/components/BindingPolicy/BPTable.tsx
- src/components/BindingPolicy/Dialogs/BPHeader.tsx
- src/components/BindingPolicy/Dialogs/EditBindingPolicyDialog.tsx
- src/components/BindingPolicy/PreviewDialog.tsx
- src/components/ClustersTable.tsx
- src/components/CreateBindingPolicyDialog.tsx
- src/pages/BP.tsx
- src/pages/WDS.tsx
Improved dark mode styling for the **Managed Clusters** and **Overview** section. Addressed edge cases, ensuring proper dark mode support for filters and preview matches. Also adjusted the text size of the table header names for better readability. Additionally, implemented dark mode in the **Create Binding Policy** and **Edit Binding Policy** pages within the **Overview** section, ensuring consistency across these pages.
Fixes #189
https://github.com/user-attachments/assets/31da23f6-d66f-4085-b863-864d710bb792
No changes were made to the light mode; it remains as before. Dark mode now ensures better readability and consistency across pages, including the **Create Binding Policy** and **Edit Binding Policy** pages. Let me know if any further refinements are needed.
> Improve Dark Mode Support in Managed Clusters, Overview,  Create and edit Binding Policy Pages

- src/components/ImportClusters.tsx
Added an inside box element around the Select Kubeconfig file, along with putting a background color to make it contrast against the button and white background color. I also added drop shadows to all the buttons in the Kubeconfig and API/URL tabs.
Should I get rid of the border on the inside box with the gray background color?
I'll also be adding drop shadows to the buttons in the other tabs.
> Added inside box element in Kubeconfig pop-up tab, and added drop shadows to buttons

- backend/main.go
- backend/namespace/namespace.go
- backend/namespace/resources/service.go
Added WebSocket support for real-time updates on Kubernetes resources, eliminating the need for polling.
- Implemented a WebSocket server at `/ws/namespaces`  
- Added Kubernetes Informers/Watch API to track resource changes  
- Broadcast updates (Added, Modified, Deleted events) to WebSocket clients  
- Managed multiple WebSocket connections  
- Implemented reconnection handling and heartbeat  
1. Run the application locally.  
2. Open a WebSocket client (e.g., Postman, wscat) and connect to `ws://localhost:4000/ws/namespaces`.  
3. Apply changes to Kubernetes resources using `kubectl apply -f <resource.yaml>`.  
4. Verify if the WebSocket client receives updates.  
Closes #202
> Added WebSocket support for real-time updates on Kubernetes resources, eliminating the need for polling.

- backend/Dockerfile
Upgrade the Go version in the Dockerfile to ensure compatibility with the latest features and improvements.
Fixes #229
> Update Go version in Dockerfile to 1.23

- src/components/ImportClusters.tsx
This PR fixes an issue where the **"Cluster Name"** label was getting partially hidden when the input field was focused.  
The fix involves adjusting the **flex and overflow properties** to ensure the label remains fully visible.  
Fixes #238
- ✅ Added `overflow: 'visible'` to prevent label clipping.  
- ✅ Moved `overflowY: 'auto'` to `tabContentStyles` for correct scrolling behavior.  
- ✅ Ensured `flexGrow: 1` and `minHeight: 0` to prevent shrinking issues.  
**Before (Issue Present)**  
**After (Fixed)**  
- This fix was tested with multiple input fields to ensure no regressions.  
- If there are any additional UI changes required, let me know! 🚀
>  Ensure Cluster Name Label is Fully Visible on Focus

- backend/main.go
- backend/routes/bp.go
The Binding Policy routes was defined twice in main.go and in the routes/bp.go
- Remove the duplication of the routes. Moved all the binding policy routes to routes/bp.go
> Fixed the issue of duplicate routes of binding policy

- backend/namespace/namespace.go
`Enhance /api/namespaces/:name to Show All Resources`  
This PR improves the `/api/namespaces/:name` API route by ensuring it retrieves and displays all related resources within a namespace. Previously, some resources were missing, but now the API includes:  
- Pods  
- Deployments  
- Services  
- ConfigMaps  
- Secrets  
- StatefulSets  
- PersistentVolumeClaims (PVCs)  
- Roles & RoleBindings  
- Ingresses  
✅ Updated `GetNamespaceDetails` to fetch all associated resources.  
✅ Added missing Kubernetes resource retrievals.  
✅ Ensured caching with Redis for improved performance.  
✅ Enhanced error handling and logging for better debugging.  
✔️ Tested on a live Kubernetes cluster.  
✔️ Verified response structure includes all expected resources.  
✔️ Cached responses correctly update …
> Enhance GetNamespaceDetails to return comprehensive namespace information

- backend/routes/services.go
- backend/wds/deployment/common.go
- backend/wds/resources/services.go
I have this in my backlog now its done 
```json
{
"metadata": {
"name": "my-service",
"namespace": "default",
"uid": "260101f1-079a-4eaa-a83d-d15d92822dfb",
"resourceVersion": "23210",
"creationTimestamp": "2025-03-02T01:56:07+05:30",
"labels": {
"app": "my-app",
"environment": "production",
"tier": "frontend"
},
"annotations": {
"prometheus.io/port": "9114",
"prometheus.io/scrape": "true",
"service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http",
"service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:us-west-2:123456789012:certificate/abc123-example",
"service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "https"
},
"managedFields": [
{
"manager": "main",
"operation": "Update",
"apiVersion": "v1",
"time": "2025-03-02T02:03:48+05:30",
"fieldsType": …
```
> feat: added update service and updated the get/list routes response

- backend/k8s/resources.go
- backend/routes/resources.go
- backend/routes/setup.go
- backend/utils/parser.go
This PR introduces a full CRUD API to manage Kubernetes resources such as Deployments, Services, ConfigMaps, Secrets, and Ingresses via RESTful endpoints. The implementation is built using the **Gin framework** and the **Kubernetes Go client (`client-go`)**, ensuring efficient and secure communication with the cluster.
- **Create Resource (`POST`)**
- **Get a Single Resource (`GET`)**
- **List All Resources (`GET`)**
- **Update Resource (`PUT`)**
- **Delete Resource (`DELETE`)**
- **Supports JSON and YAML input**
- **Proper error handling for unsupported resource types**
**Endpoint:**
```plaintext
POST /api/v1/namespaces/{namespace}/resources/{resourceType}
```
**Request Body (JSON Example for Deployment):**
```json
{
"apiVersion": "apps/v1",
"kind": "Deployment",
"metadata": {
"name": …
```
> 🚀 Add Full CRUD API for Kubernetes Resources 

- backend/api/deploy.go
- backend/k8s/deployer.go
**Title:** Add Dry Run Option and Enhance Resource Discovery  
This PR introduces a **dry run** option in the deployment process, allowing users to simulate deployments without making actual changes. Additionally, it enhances the resource handling by leveraging the Kubernetes **Discovery API** to retrieve and organize deployed resources in a hierarchical structure.  
- **Dry Run Mode:** Users can now specify a `dry_run` parameter via API to preview the deployment process without applying changes.  
- **Kubernetes Discovery API Integration:** Improved resource handling by fetching all Kubernetes objects hierarchically.  
- **Enhanced Logging & Response Structure:** More detailed responses for both actual and dry-run deployments.  
1. Use Postman or `curl` to send a …
>  Add Dry Run Option and Enhance Resource Discovery  

- backend/wds/bp/handlers.go
- backend/wds/bp/utils.go
This PR enhances the binding policy system to support targeting specific workload instances alongside general resource types. It allows to define individual workloads by apiVersion, kind, name, and namespace, providing more granular control over which resources are managed.
Fixes #312 
- Add WorkloadInfo struct to represent individual targeted workloads
- Extend StoredBindingPolicy to include specific workloads field
- Implement YAML parsing for the workloads section in binding policies
- Add consistent lowercase conversion for resource names
- Implement fallback strategies for retrieving workload information
> Add support for specific workloads in binding policies

- src/components/BindingPolicy/AvailableItemsPanel.tsx
- src/components/BindingPolicy/CanvasItems.tsx
- src/components/BindingPolicy/ClusterPanel.tsx
- src/components/BindingPolicy/ConnectionIcon.tsx
- src/components/BindingPolicy/ConnectionManager.tsx
- src/components/BindingPolicy/ItemTooltip.tsx
- src/components/BindingPolicy/KubernetesIcon.tsx
- src/components/BindingPolicy/PolicyCanvas.tsx
- src/components/BindingPolicy/PolicyDragDropContainer.tsx
- src/components/BindingPolicy/QuickPolicyDialog.tsx
- src/components/BindingPolicy/WorkloadPanel.tsx
- src/components/BindingPolicy/nodes/ClusterNode.tsx
- src/components/BindingPolicy/nodes/PolicyNode.tsx
- src/components/BindingPolicy/nodes/WorkloadNode.tsx
- src/pages/BP.tsx
- src/stores/connectionManagerStore.ts
Removed the connection mode in drag and drop binding policy. Fixed lint warnings and also improved the layout.
Fixes #342 
- Removed the connection mode. Instead clusters and workloads can be directly mapped.
- Fixed the lint warnings.
- Added customize icons for the clusters and workloads.
- Improve the layout. 
> Removed the connection mode in drag and drop

- backend/api/deploy.go
- backend/api/handlers.go
- backend/auth/auth.go
- backend/go.mod
- backend/main.go
- backend/middleware/auth.go
- backend/models/user.go
- backend/namespace/namespace.go
- backend/namespace/resources/service.go
- backend/redis/redis.go
- backend/routes/bp.go
- backend/routes/cluster.go
- backend/routes/deployment.go
- backend/routes/gitops.go
- backend/routes/jwt.go
- backend/routes/namespace.go
- backend/routes/resources.go
- backend/services/clusterService.go
- backend/utils/jwt.go
- backend/wds/bp/handlers.go
- backend/wds/bp/utils.go
- backend/wds/deployment/common.go
- backend/wds/deployment/details.go
- backend/wds/deployment/logs.go
- backend/wds/deployment/status.go
**Title:**  
Chore: Update module name to `github.com/kubestellar/ui`  
This PR updates the Go module name from `github.com/katamyra/kubestellarUI` to `github.com/kubestellar/ui` to align with the new repository structure.  
- Updated `go.mod` to reflect the new module name.  
- Replaced all occurrences of `github.com/katamyra/kubestellarUI` with `github.com/kubestellar/ui`.  
- Ran `go mod tidy` and `go mod vendor` to update dependencies.  
- Verified that the project builds successfully.  
_(Attach any relevant logs or screenshots)_  
Closes #376
_(Mention any additional concerns or testing notes)_
> Refactor import paths to new module structure

- backend/routes/setup.go
- backend/routes/wecs.go
- backend/wecs/wecs.go
**Title:** [WECS] Introduce WebSocket Routes for Streaming Cluster Data and Pod Logs
Fixes : #380
**Description:**
This PR introduces two new WebSocket endpoints to enhance real-time data access for users by streaming Kubernetes cluster data and pod logs separately. These changes aim to improve performance and provide clearer data separation:
1. **/ws/data:**  
- Streams hierarchical pod data grouped by cluster and namespace.
- Returns raw pod JSON details without logs for fast, efficient data retrieval.
2. **/ws/logs:**  
- Streams full pod logs for a specified pod.
- Requires query parameters (`cluster`, `namespace`, and `pod`) to select the target pod.
**Changes Made:**
- Added a new function `FastStreamK8sData` to fetch and stream hierarchical pod data using concurrent API calls.
- …
>  [WECS] Introduce WebSocket Routes for Streaming Cluster Data and Pod Logs

- src/components/ImportClusters.tsx
- src/components/login/KubeStellarLayout.tsx
- Eliminated the YAML tab and its associated content
- Removed state variables specific to the YAML tab (fileType and editorContent)
- Improved Tab Navigation
- Renamed tab options to semantic values for better code readability
- Changed from "option2", "option3", "option4" to "kubeconfig", "apiurl", "manual"
- Added fallback logic to ensure a valid tab is always selected
- Replaced Material UI Button with a simpler Box component for the close (X) icon
- Removed distracting hover/click effects
- Implemented a subtle color transition on hover for better usability
- Maintained consistent positioning and functionality
> Removed: Yaml and cross hover shape

- src/components/CreateOptions.tsx
- src/components/Workloads/GitHubTab.tsx
Change all instances of the default branch name from 'master' to 'main' in the CreateOptions and GitHubTab components. Update related placeholder text accordingly.
Fixes #403
> Update default branch name to 'main'

- backend/k8s/deployer.go
**Title:** Ensure Namespace Exists Before Applying Resources in DeployManifests it  will create if don't exit   
This PR fixes an issue where **DeployManifests** fails if the specified namespace does not exist. The update ensures that the namespace is created before applying resources.  
- Added a check to verify if the namespace exists.  
- If the namespace is missing, it is created before applying manifests.  
- Improved logging for better debugging.  
1. Deploy resources using **DeployManifests** to a cluster without the namespace.  
2. Verify that the namespace is created automatically.  
3. Ensure resources are applied successfully.  
Fixes #406
> Add namespace existence check in DeployManifests

- backend/k8s/resources.go
In this pull request #408 , i changed getGVR logic which introduce a bug which all time gives invalid resource types 
Fixes #412
Under #52 
> fix the getGVR function bug

- backend/wds/bp/handlers.go
- backend/wds/bp/utils.go
this fixes the inactive state reported for BP from backend of KS UI. @kunal-511 you can update the frontend now to use this endpoint it should reflect the latest state. You might need to call it multiple times because state becomes active after some secs. after controller reconciles it fully.
closes #441 
> fixes active inactive issue for BP backend

- src/components/BindingPolicy/BPTable.tsx
- src/components/BindingPolicy/BPVisualization.tsx
- src/components/BindingPolicy/Dialogs/DeleteDialog.tsx
- src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
- src/hooks/queries/useBPQueries.ts
- src/pages/BP.tsx
Fixed the binding policy status issue with some dark mode issues and the BPVisualization
Fixes #443 
- Fixed the dark mode issue in delete dialog box.
- Fixed the delete button crust in safari browser.
- Updated the bp status which was coming inactive always
- Updated BPVisualization to show create bp if no bp added 
- Removed all the workloads from default namespace in drag and drop
> Fixed the binding policy status issue with some dark mode issues

- README.md
In README for the frotnend we specify "example.env" which is not present. The actual name of the file is .env.example. Here I corrected the readme.md
Fixes #448
> example.env is not present. The actual name of the file is .env.example

- src/components/Header.tsx
- tailwind.config.js
Before even on light mode, the signout button shows dark background which is fixed.
Fixed the fullscreen issue
Fixes #458
> fixed button and fullscreen issue

- backend/k8s/resources.go
- backend/wds/bp/handlers.go
- src/components/BindingPolicy/AvailableItemsPanel.tsx
- src/components/BindingPolicy/CanvasItems.tsx
- src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
- src/components/BindingPolicy/PolicyCanvas.tsx
- src/components/BindingPolicy/PolicyDragDropContainer.tsx
- src/components/BindingPolicy/WorkloadPanel.tsx
- src/components/CreateOptions.tsx
- src/components/Workloads/UploadFileTab.tsx
- src/components/Workloads/YamlTab.tsx
- src/hooks/queries/useBPQueries.ts
- src/hooks/queries/useWDSQueries.ts
- src/pages/BP.tsx
- src/types/bindingPolicy.ts
Now the drag and drop binding policy is properly working targeting the cluster and workload using the default labels. 
Fixes #485 
- Updated the backend to correctly se the workload.
- Updated the frontend to match the required format needed by backend to create binding policy using quick create.
- Updated the binding policy canvas to get reset after creating a binding policy.
- Showing labels section when a workload is available in drag and drop
> Fixed the drag and drop binding policy

- backend/main.go
**Title:** Remove Duplicate `/api/deploy` Endpoint from Go API
**Description:**
This PR removes a duplicate registration of the `/api/deploy` endpoint from the Go backend. Having multiple registrations for the same route can lead to unexpected routing behavior or override issues.
- Removed the redundant `/api/deploy` route handler.
- Verified that the retained handler is the correct and intended implementation.
- Cleaned up any unused imports or functions associated with the duplicate.
- Confirmed that existing functionality for `/api/deploy` remains intact.
This resolves internal routing conflicts and improves the maintainability of the API layer.
fixes #496
> Remove Duplicate `/api/deploy` Endpoint from Go API

- backend/api/deploy.go
- backend/main.go
Add deployment ID support to DeployHandler
This PR adds support for custom deployment IDs in the DeployHandler function, completing the CRUD workflow for GitHub deployments. Users can now specify a custom ID when creating deployments and retrieve this ID in responses for easier management and tracking.
- Modified `DeployHandler` to accept an optional `id` query parameter
- Updated ID generation logic to use the provided ID or generate one if not specified
- Added deployment ID to all response objects (both dry runs and actual deployments)
- Maintained backward compatibility with existing deployments
- Tested deployment creation with custom ID
- Verified auto-generation still works when no ID is provided
- Confirmed ID appears in response objects
- Validated integration with existing …
> Add deployment ID support to DeployHandler

- backend/wds/bp/handlers.go
- src/components/BindingPolicy/BPTable.tsx
- src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
- src/components/CreateOptions.tsx
- src/hooks/queries/useBPQueries.ts
- src/pages/BP.tsx
- src/types/bindingPolicy.ts
Fixed the issue of different yaml shown at the editor and the actual binding policy creator
Fixes #500 
- Fixed the issue was policy detail dialog was not taking the content from the correct api.
- updated the backed get all binding policy to send correct policy depend on the creation method.
> Fixed the issue of different yaml showing in binding policy

- src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
- src/components/BindingPolicy/PolicyDragDropContainer.tsx
- src/hooks/queries/useBPQueries.ts
Removed the hard coded labels sent to the backend to create binding policy through drag and drop.
Fixes #510 
- Updated the api body to extract label of both cluster and workload automatically.
- Made the drag and drop defualt option to create binding policy.
> Removed the hardcoded labels from the binding policy creation

- backend/k8s/resources.go
- src/components/CreateOptions.tsx
Updated the label name to - `kubernetes.io/kubestellar.workload.name`
Fixes https://github.com/kubestellar/ui/issues/484
Under #52 
> updated the custom label name in raw yaml and upload file

- src/components/login/LoginForm.tsx
Previously, icons in the username and password fields shifted downward when error messages appeared due to increased container height affecting absolute positioning.
This commit introduces an inner div to isolate inputs and icons, ensuring consistent alignment by separating error messages from the positioning context.
Fixes: #509.
| Before   | After                                                                 |
|---------|-----------------------------------------------------------------------------|
| ![](https://github.com/user-attachments/assets/04e1dd0f-4276-4087-a84e-41fa06fbcf4a) | ![](https://github.com/user-attachments/assets/bf31e83f-2cb7-4431-8375-44af181db3a7) |
> fix: Stabilize icon alignment in LoginForm input fields.

- backend/api/deploy.go
- backend/k8s/deployer.go
- backend/redis/redis.go
`feature/workload-labels`
This PR implements the ability to assign a workload label to resources during deployment from all sources: file-based manifests, GitHub repositories, and Helm charts. The label is applied at creation time and stored with deployment records.
- Added `workload_label` as an input parameter for all deployment methods
- If a label is not provided, the system uses sensible defaults:
- For GitHub: Uses the repository name as the label
- For Helm: Uses the chart name as the label
- Modified the `DeployManifests` function to apply `kubestellar.io/workload` label to all deployed resources
- Updated the Helm deployment logic to add labels through various Helm values approaches
- Added Redis support for workload labels to maintain state between operations
- Updated ConfigMap …
> # Add support for workload labels across all deployment methods

- src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
Remove unwanted white border in YAML tab of CreateBindingPolicyDialog
Fixes: #521.
> fix: Remove white border in YAML tab of CreateBindingPolicyDialog.

- src/components/ContextDropdown.tsx
- src/components/TreeViewComponent.tsx
- src/components/WecsTopology.tsx
This PR improves the visibility of UI elements in dark mode by enhancing theme-aware styling for icons and buttons. Currently, several UI controls are difficult to see or nearly invisible when using dark mode, particularly the list/grid view toggle icons and dropdown selectors.
Fixes UI visibility issues in dark mode
After:
[Image showing improved icon visibility in dark mode]
These changes only affect the UI appearance in dark mode and do not alter any functional behavior. The approach used maintains current styling in light mode while enhancing visibility in dark mode through conditional theme-aware styling.
> Fix: Improve icon visibility in dark mode for dropdown and view toggles

- src/components/ListViewComponent.tsx
This PR addresses an issue with the list view rendering in dark mode on the Manage Workloads page. Currently, the list view displays with incorrect background colors when in dark mode, causing poor contrast and visibility problems for users.
Fixes UI visibility issues in dark mode
Fixes #559 
- Fixed list view item backgrounds to properly respect dark mode theme
- Updated text colors in list items for better readability in dark mode
- Added proper hover state styling for list items in dark mode
- Ensured consistent styling between hover and non-hover states
- Improved empty state message visibility in dark mode
Before: List view items show with white backgrounds in dark mode, creating poor contrast and readability issues.
After: List view items properly display with dark backgrounds …
> Fix: Improve dark mode UI with proper contrast for list view and icons

- src/components/BindingPolicy/BPTable.tsx
- src/pages/BP.tsx
This PR fixes issues with the binding policy status filtering functionality. Previously, when selecting a status filter (Active, Inactive, Pending), the system would sometimes only show one matching policy when there should be multiple, or no policies at all for certain status values.
Fixes UI filtering issues in Binding Policy management
After: All policies matching the selected status filter are now displayed correctly.
This fix addresses a subtle issue where the component was performing filtering at two levels - first in the BP.tsx parent component, then again in the BPTable.tsx child component. This double filtering with slightly different implementations was causing inconsistent results. The solution was to consolidate all …
> Fix: Resolve binding policy filter issues with status matching

- src/components/BindingPolicy/ClusterPanel.tsx
- src/components/BindingPolicy/WorkloadPanel.tsx
Added the search funcctionality for both clusters and workload labels in the drag and drop binding policy
Fixes #576 
- Added a search button and search functionality at the top for both the cluster and workloads labels section.
> Added the search funcctionality for both clusters and workload labels

- src/components/BindingPolicy/PolicyCanvas.tsx
This PR enhances the binding policy canvas UI by adding individual delete buttons to cluster and workload items. Currently, users can only clear the entire canvas, which creates a poor user experience when they want to remove just one or a few items.
Fixes #586  
[Screencast from 19-04-25 02:21:26 AM IST.webm](https://github.com/user-attachments/assets/e07d41bf-9619-4df9-94f5-55e3e3e96001)
This change improves user experience significantly by allowing selective removal of items from the canvas instead of requiring users to clear the entire canvas when they only need to remove one item.
> added individual delete button to the clusters and workload

- src/components/BindingPolicy/ClusterPanel.tsx
- src/components/BindingPolicy/Dialogs/BPHeader.tsx
- src/components/BindingPolicy/WorkloadPanel.tsx
Added feature to directly edit the cluster labels from the click and drop binding policy
Partially Fixes: 592
- Added the functionality to edit the cluster labels directly from binding policy.
- Removed some icons as discussed.
> Added feature to directly edit the cluster labels 

- backend/api/deploy.go
Fix issue where custom `workload_label` values in request bodies were ignored and defaulting to extracted values from repository URLs or chart names.
- Added debug logging to track `workload_label` values
- Fixed conditional logic to respect user-provided labels
- Enhanced validation for consistent label application
- Improved logging for easier troubleshooting
Fixes #610
This fix maintains backward compatibility - deployments without specified labels will continue using the default extraction behavior.
> Fix: Properly Respect User-Provided Workload Labels in Deployment Handlers

- src/components/CreateOptions.tsx
- src/components/Workloads/GitHubTab.tsx
- src/components/Workloads/HelmTab/CreateOwnHelmForm.tsx
- src/components/Workloads/HelmTab/HelmTab.tsx
This PR introduces label support functionality for both the GitHub and Helm tab sections. It allows users to assign and manage labels from now github and helm tab.
> feat: add label support in GitHub and Helm tab

- backend/wds/bp/handlers.go
- src/components/BindingPolicy/BPTable.tsx
- src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
- src/components/BindingPolicy/KubernetesIcon.tsx
- src/components/BindingPolicy/PolicyCanvas.tsx
- src/components/BindingPolicy/PolicyDragDropContainer.tsx
- src/components/BindingPolicy/PolicyPanels.tsx
- src/components/BindingPolicy/WorkloadPanel.tsx
- src/hooks/queries/useBPQueries.ts
Use the new api to show the cluster scope objects in the workload panel of the click and drop Binding Policy.
Fixes #622 
- Restructured everything in the workload panel.
- Integrated new api for the workloads which includes cluster scoped objects.
- Made changes in backend to deploy the CRD's  using click and drop method.
> Added cluster Scope objects in workload Panel

- src/components/WecsDetailsPanel.tsx
- src/components/WecsTopology.tsx
… and context menu items based on node type
Fixes #636  
- As discussed with @clubanderson , I have disabled log rendering for clusters since we currently don't have logs available for clusters.
- Fixed the behavior of the menu item button.
> fix : fix for menu item in 'Deployed workloads' and update WecsDetailsPanel and WecsTopology to conditionally render logs 

- backend/k8s/deployer.go
Added labels for:
- Helm chart namespace
- Artifact Hub namespace
- GitHub chart namespace
Closes #664
- Added namespace labels in `Chart.yaml`
- Updated Artifact Hub annotations
- Ensured metadata consistency with GitHub chart reference
_Please attach screenshots or relevant logs here._
Let me know if any additional labels or namespace conventions should be followed.
> Add Namespace Labels for Helm Chart, Artifact Hub, and GitHub Chart

- backend/api/deploy.go
- backend/go.mod
- backend/k8s/deployer.go
- backend/k8s/resources.go
Refactor the DeployHandler to clone GitHub repositories directly, enhancing error handling and managing workload labels more effectively. This change streamlines the deployment process and improves reliability.
Fixex #675
> Refactor DeployHandler for improved GitHub repository handling

- src/components/CreateOptions.tsx
- src/components/Workloads/UploadFileTab.tsx
- src/components/Workloads/YamlTab.tsx
This PR fixes the label key in "initialEditorContent"
Synchronised changes between workload label inputbox and editor
https://github.com/user-attachments/assets/6daae209-13b4-4c94-944b-59fee9c48b51
Same changes for the input file tab
Fixes #673 
> Synchronised changes between workload label inputbox and editor in yaml and input file tab

- src/components/BindingPolicy/WorkloadPanel.tsx
Now showing all the labels by default in workload panel and only filter them on basis of "kubestellar.io/workload" if the search is clicked.
Fixes #726 
> Updated the label filtering logic

- backend/Dockerfile
This PR updates the golang base image in the Dockerfile from Go 1.23.x to Go 1.24.2 to resolve a build failure caused by a version mismatch. The go.mod file specifies go 1.24, but the current base image provides go 1.23.9.
Fixes #737
> Upgrade Go base image to v1.24.2 to match go.mod requirements

- backend/wecs/exec.go
We are selecting only one container always which is problematic for us, we need to go through some dynamic way to check first this pod in which containers running and then select the container and then we will do the execution to pods(container)
Fixes #733
Part of #52 
> fix: removed the hardcoded container selection from exec-in-pods

- backend/routes/resources.go
- backend/wds/list.go
Updated to show all k8s workloads with the cluster-scoped object and I removed the ListAllResourcesDetails reason we are using the sse way to get all objects
Fixes #743
Under #52
> fix: updated the list-view api to show all k8s workload resources

- src/components/Workloads/HelmTab/PopularHelmChartsForm.tsx
This PR addresses visual inconsistencies in the "Deploy from popular Helm charts" section within the Helm tab when using dark mode. The section now properly adapts to the theme for better readability and UI consistency.
> Fix dark mode styling in 'Deploy from popular Helm charts' section

- src/routes/routes-config.tsx
Eliminate the KubeStellarStatusChecker component from the routes configuration to streamline the routing structure.
Fixes #757
> Remove KubeStellarStatusChecker from routes configuration

- src/components/BindingPolicy/ClusterDialogs.tsx
- src/components/BindingPolicy/ClusterLabelsList.tsx
- src/components/BindingPolicy/ClusterPanel.tsx
- src/components/BindingPolicy/ClusterPanelHeader.tsx
- src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
- src/components/BindingPolicy/PolicyDragDropContainer.tsx
- src/components/BindingPolicy/WorkloadPanel.tsx
- src/components/ClustersTable.tsx
- src/components/TreeViewComponent.tsx
- src/hooks/queries/useBPQueries.ts
- src/pages/ITS.tsx
Added a bulk edit mode where multiple resources can be assigned the labels directly from the click and drop binding policy. Also updated the import cluster and create workload button in click and drop.
Fixes: #706 and #755
- Implemented the bulk edit mode for both clusters and workloads.
- Split the cluster panel component into 3 sub components.
-  Now the import button in BP takes directly to import cluster dialog.
-  Same for the create workload button in BP takes directly to the create workload dialog.
> Added Bulk edit Mode

- src/components/WecsDetailsPanel.tsx
- src/components/WecsTopology.tsx
This PR improves the UX by setting the Summary tab as the default view when a user clicks on any node in the topology. Additionally, it removes/hides the Logs tab for all objects except Pod objects, reducing clutter for unsupported views.
> Add Summary Tab as Initial View for Node Clicks and Hide Logs Tab for Non-Pod Objects

- backend/installer/kubestellar_status.go
The KubeStellar status checker function (`CheckKubeStellarStatus()`) currently reports a success message ("KubeStellar context and required namespaces verified") even when the required namespaces (`wds1-system` and `its1-system`) are not found.
This leads to misleading status reports where the message indicates success but the boolean flags correctly show that the namespaces are missing:
```json
{"context":"k3d-kubeflex","contextFound":true,"wds1Namespace":false,"its1Namespace":false,"allReady":false,"message":"KubeStellar context and required namespaces verified"}
```
This PR updates the status message logic to accurately reflect the state of the verification:
1. Only show the success message when both required namespaces are actually found
2. Show a clearer error message when namespaces …
> Refactor status message handling in CheckKubeStellarStatus function

- src/components/TreeViewComponent.tsx
- src/components/WecsTopology.tsx
This PR addresses visual inconsistencies in dark/light mode themes across the application. It ensures proper styling of:
Objects and nodes in the Remote Cluster View and Dropdown menus (ensuring readability and contrast) in the Stage workloads and Remote cluster view.
> Fix Dark/Light Mode Styling of Dropdown Components in Remote Cluster Objects, Stage Workloads also for Nodes.

- src/pages/InstallationPage.tsx
Fixes #767
- *TabButton Component:*
- Added a new disabled prop to control tab interactivity.
- Updated styling to visually indicate a disabled (locked) state for tabs.
- *Prerequisites Tab Behavior:*
- The *Prerequisites* tab is now *disabled* when skipPrerequisitesCheck is true.
- This ensures users who do not need to check prerequisites are guided appropriately.
- *Installation Tab Enhancements:*
- Added a *prominent "Install Prerequisites First"* section at the top of the Installation tab:
- *Clear heading and descriptive text*
-  *Visual FileText icon* for clarity and visual emphasis
-  A *button labeled "View Install Prerequisites"*
-  Redirects users to the official KubeStellar prerequisites documentation
- Styled to draw attention and guide users effectively
- Docker users will …
> Enhance Prerequisites Accessibility and Improve Tab UX

- backend/installer/kubestellar_status.go
Title: Support Multiple Context Types in KubeStellar Status Check
Description:
This PR enhances the `CheckKubeStellarStatus` function to support multiple context types ("kubeflex", "kind", and "k3d") and properly handle environments with multiple available contexts.
- Modified the context check to look for any of the specified compatible types
- Implemented logic to check all available contexts
- Return early with success when any fully functional context is found
- Maintain backward compatibility with the existing API
- Improved error messages to be more descriptive
1. Set up an environment with multiple kubectl contexts (at least one should have a compatible type)
2. Ensure at least one context has both required namespaces
3. Run the installer and verify it correctly identifies the …
> Update KubeStellar status check for multiple context types

- src/components/Header.tsx
- src/components/TreeViewComponent.tsx
- src/components/WecsTopology.tsx
- src/components/ui/FullScreenToggle.tsx
- src/components/ui/HeaderSkeleton.tsx
Fixes #797
Added a reusable FullScreen toggle component to enhance the user experience in both WDS and WECS  views. The component provides a consistent and accessible way to toggle fullscreen mode across different parts of the application.
- Created a new reusable `FullScreenToggle` component in `src/components/ui/FullScreenToggle.tsx`
- Implemented with TypeScript for better type safety and maintainability
- Added comprehensive prop interface for flexible usage
- **Fullscreen Toggle Functionality**
- Support for both container-specific and document-level fullscreen
- Cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- Proper cleanup of event listeners
- Error handling for unsupported browsers
- **Accessibility**
- ARIA attributes for screen readers
- Keyboard navigation support …
> Feat: Full Screen in WDS, WECS Toggle Component Implementation and Improvements

- .prettierignore
This PR adds the `vendor` directory to the [.prettierignore] to prevent Prettier from checking files in the vendor directory during pre-commit hooks. This is a common practice to avoid unnecessary formatting of third-party code.
Fixes #849
- Added `vendor` to [.prettierignore] to exclude vendor directory from Prettier checks
> fix: add vendor folder to .prettierignore

- src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
- src/hooks/queries/useBPQueries.ts
- src/pages/BP.tsx
Removed the bottom toast on delete binding policy.
Updated the create bp dialog to do not close on error just show the error
Made the error message on fail more clear
> Updated the Closure of Create Bp dialog

- Dockerfile
- backend/.env.example
- backend/k8s/resources.go
- backend/main.go
- docker-compose.yml
This PR fixes the critical WebSocket connection hijacking error and adds configurable CORS origin support through environment variables.
Fixes #903
- **File**: `LogWorkloads` handler function
- **Problem**: `c.JSON()` calls after `upgrader.Upgrade()` caused hijacking errors
- **Solution**: Moved all validation logic before WebSocket upgrade
- **Impact**: Eliminates "connection has been hijacked" errors
- **File**: `main.go` - `ZapMiddleware()`
- **Added**: WebSocket detection with `isWebSocketUpgrade()` helper
- **Improvement**: Proper logging for WebSocket connections without interference
- **File**: `main.go` - CORS middleware
- **Added**: `CORS_ALLOWED_ORIGIN` environment variable support
- **Benefit**: Configurable frontend URLs for different environments
- **Fixes #[ISSUE_NUMBER]**: …
> Fix WebSocket Connection Hijacking and Add CORS Environment Variable Support

- Dockerfile
- docker-compose.yml
Fixes issue #912 where Docker build was failing because `VITE_BASE_URL` environment variable was not available during the build stage.
The `vite-plugin-environment` plugin was throwing an error during `npm run build` because environment variables defined in `docker-compose.yml` are only available at runtime, not during the Docker build process.
```
Error: vite-plugin-environment: the `VITE_BASE_URL` environment variable is undefined.
```
- Updated `Dockerfile` to accept build arguments for all required environment variables
- Modified `docker-compose.yml` to pass environment variables as build arguments
- Ensured all Vite environment variables are available during the build stage
- Added `ARG` declarations for all Vite environment variables
- Set `ENV` variables from build arguments
- …
> Refactor Dockerfile and docker-compose for build arguments

- README.md
**Summary**  
This PR adds a note to the README to help WSL users who may experience issues with Docker Desktop not detecting KubeStellar demo clusters. It outlines the potential cause (communication issues between Docker Desktop and WSL) and provides a step-by-step workaround.
**Changes Made**
- Added a new "Note for WSL Users" section to the README.
- Included troubleshooting steps and a recommended workaround using Docker installed directly inside WSL.
**Reason for the Change**  
Several users have reported that even after successfully installing KubeStellar demo clusters, they are not detected by Docker Desktop. This guide will help users quickly diagnose and fix the issue, improving onboarding and user experience.
**Checklist**
**Related Issues**  
Fixes: #947
> Add WSL Troubleshooting Note to README

- src/components/Wds_Topology/ZoomControls.tsx
This PR addresses the issue where the zoom controls behave in a buggy manner
1. On loading of the canvas , the zoom label shows an incorrect value
2. Label fails to change value upon zooming in/out using Ctrl  + pinch on touchpad
Fixes #971 
[Screencast from 2025-06-03 23-15-08.webm](https://github.com/user-attachments/assets/73d8fcce-5461-42aa-87b8-ed755c8889c3)
> fix: buggy behaviour of zoom controls

- .prettierignore
This PR fixes the auto format by prettier on yaml/yml files which were wrongly formatted and breaking Helm template syntax.
Fixes #1135
> fix: Ignore yaml file by prettier

- src/components/CommandPalette.tsx
- src/locales/strings.en.json
This PR adds the missing field Plugin Manager into search(Command palette)
Fixes  #1159 
> feat: Add plugin manager field into search(command palette)

- frontend/src/components/CommandPalette.tsx
There was an inconsistent blur effect across the Command Palette UI. When triggered, the entire page would blur unevenly — some areas were overly blurred while others had no blur — leading to a poor user experience.
This PR addresses the issue by ensuring that only the Command Palette is visually focused when opened. It **disables background scroll** and **removes the full-page blur effect**, applying a consistent and subtle overlay instead. When the user clicks outside the Command Palette (e.g., on the home screen), the palette closes and the overlay is removed, restoring the original view.
Fixes :- 
#1024 
✨ Consistent Blur Effect: Focused blur is applied only behind the Command Palette, avoiding full-page or uneven blur artifacts. …
> CommandPalette UI Rectified on Blur Effect

- backend/test/models/cluster_test.go
- backend/test/models/namespace_test.go
- backend/test/models/user_test.go
Added unit tests for all backend model structs (`User`, `Cluster`, `Namespace`) in the `models` package. These tests cover struct initialization, JSON marshaling/unmarshaling, and password hashing logic. This ensures data integrity, catches accidental changes to struct fields or tags, and improves maintainability.
Fixes #1007 
- Added `user_test.go`, `cluster_test.go`, and `namespace_test.go` in `backend/test/models/`.
- Tests verify:
- Struct field correctness and initialization.
- JSON serialization/deserialization and tag consistency.
- Password hashing and verification logic.
- Nested struct and API contract validation.
---
> ✨feat: add unit tests for Cluster, Namespace, and User models

- frontend/src/components/plugin/FeedbackModel.tsx
This PR disables Cancel button to act like submit button. 
Fixes #1255
> bug: Fix cancel button issue of feedback form

- frontend/src/components/ProfileSection.tsx
This PR fixes the issue where the "Change Password" modal in the ProfileSection component would shift position when the page was scrolled. The modal is now rendered using a React portal directly within `ProfileSection.tsx`, ensuring it remains perfectly centered on the viewport regardless of page scroll. The background remains scrollable as expected.
Fixes #1260 
https://github.com/user-attachments/assets/fb05f590-eefe-4f04-bff3-5d8e8eb5e520
**Before:**  
Modal would shift upward when scrolling the page.
**After:**  
Modal remains perfectly centered, even when the page is scrolled.
> DialogFix Modal Positioning: Use Portal for Change Password Dialog in ProfileSection

- frontend/src/components/LanguageSwitcher.tsx
This PR addresses a UI bug where the Language Switcher icon appears dark even in light mode, making it hard to see. The fix ensures the icon color adjusts appropriately based on the current theme (dark or light).
Fixes #1244
> bug:fixed the language dropdown for light mode

- backend/wds/bp/utils.go
FIXES #1293
backend-1 | {"level":"info","ts":1751551121.9881978,"caller":"log/log.go:8","msg":"ectractTargetCLusters - returning clusters","count":1,"clusters":["name:cluster1"]}
backend-1 | {"level":"info","ts":1751551121.9881978,"caller":"log/log.go:8","msg":"extractTargetCLusters - returning clusters","count":1,"clusters":["name:cluster1"]}
> [Fix]: spelling mistake in log message

- frontend/src/components/Layout.tsx
- frontend/src/components/menu/MenuItem.tsx
- The sidebar jerks during the animation. The issue is, the parent should be inside a motion.div, else it will create  random animation issue 
Fixes #1296 
- wrap the sidebar by `<motion.div>`
- add no wrap to the lables , which create the sudden jerk during expansion
[Screencast from 2025-07-03 20-51-48.webm](https://github.com/user-attachments/assets/2bbc144c-a48a-4d52-aefc-9fbd588b9733)
[Screencast from 2025-07-03 21-25-46.webm](https://github.com/user-attachments/assets/bcddd2d7-933f-4bcc-b63a-6627dd6d1a7c)
> fix(animation):fix the sidebar animation sudden jerk 

- backend/log/log.go
This PR updates the logger implementation in log/log.go to correctly reflect the actual caller's file and line number in log output. Previously, all log entries pointed to log/log.go due to wrapper functions around zap. This enhancement uses zap.AddCallerSkip(1) to resolve the issue.
Fixes #1299 
- update `log/log.go` , Logs now show the true origin of the log call instead of the wrapper.
```
{"level":"info","ts":1751565962.379965,"caller":"log/log.go:8","msg":"Namespace cache miss","key":"ns_kubestellar-report_ctx_wds1_res_rbac.authorization.k8s.io_v1_roles"}
{"level":"info","ts":1751565962.574486,"caller":"log/log.go:8","msg":"Getting namespace cache","key":"ns_default_ctx_wds1_res_rbac.authorization.k8s.io_v1_roles"} …
```
> fix(logs):improve the clearity of caller field

- frontend/src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
- frontend/src/components/BindingPolicy/DeploymentConfirmationDialog.tsx
- frontend/src/components/BindingPolicy/Dialogs/EditBindingPolicyDialog.tsx
- frontend/src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
- frontend/src/components/BindingPolicy/PolicyDragDropContainer.tsx
- frontend/src/components/BindingPolicy/QuickPolicyDialog.tsx
- frontend/src/components/DynamicDetailsPanel.tsx
- frontend/src/components/WecsDetailsPanel.tsx
- frontend/src/components/Workloads/UploadFileTab.tsx
- frontend/src/components/Workloads/YamlTab.tsx
This PR completes **Part 2** of the code splitting and performance optimization process.  
It focuses on **ensuring that all heavy libraries are split into separate chunks** using Vite's manual chunking strategy.
When a user visits a route or opens a feature that requires a heavy library (like Monaco Editor or xterm), only then is that specific chunk downloaded.
> **Note:** This PR also includes the code from **Part 1: Lazy Loading and Dynamic Imports**.
---
Fixes #1095
---
- ✅ Implemented `manualChunks` in `vite.config.ts` to split heavy libraries like `Monaco Editor`, `xterm`, and `MUI` into separate chunks.
- ✅ Verified that dynamic imports and lazy loading from **Part 1** are fully functional.
- ✅ Ran `npm run build` to confirm:
- Chunks are correctly created (e.g., `vendor-mui-core`, …
> Complete Part 2: Vite chunking optimization and code splitting for heavy libraries

- frontend/src/components/ProfileSection.tsx
Fixed the theming issue in the **Change Password modal** where it always appeared in dark mode, even when the app was in light mode.  
The modal now correctly adapts to both light and dark themes using theme-aware styles.
Fixes #1322
[Screencast from 04-07-25 05:39:00 PM IST.webm](https://github.com/user-attachments/assets/6cef22fd-59dc-4895-aba5-459d9b4936b8)
> fix: update Change Password modal to support theme-aware styling

- frontend/src/components/Clusters.tsx
This PR widens the dashboard page to match the full width of other main pages in the application. Previously, the dashboard was constrained by a `max-w-7xl` class, making it appear narrower than other pages. By removing this constraint, the dashboard now utilizes the available horizontal space, providing a more consistent and visually appealing layout across the app.
Fixes #1338
[Dashboard](https://github.com/user-attachments/assets/33e76cce-2822-4c6e-95d3-11e7b0f8e422)
> Widen dashboard page to match full width of other main pages

- backend/test/routes/plugins_test.go
As we changed the identification of plugins from pluginName to pluginID, the test cases for the plugin logics also need to be updated.
I updated the `test/routes/plugins_test.go` in this commit.
Fixes #1381
> refactor: update plugin tests to use pluginID instead of pluginName

- backend/api/plugins.go
- backend/plugin/plugin.go
- backend/plugin/plugins/backup_plugin.go
- backend/plugin/plugins/manager.go
- frontend/src/components/PluginManager.tsx
- frontend/src/components/plugin/FeedbackModel.tsx
- frontend/src/plugins/PluginAPI.ts
- frontend/src/plugins/PluginLoader.tsx
- frontend/src/plugins/types.ts
Switching from pluginName to pluginID to work with the plugins.
Fixes #1351
https://github.com/user-attachments/assets/00825c5f-1a4b-4811-99fe-b41b560e3955
> refactor: switch from pluginName to pluginID in all handlers and API calls

- .github/workflows/ci.yml
- backend/Dockerfile
- frontend/Dockerfile
- scripts/helm-test.sh
This PR introduces a test script (`helm-test.sh`) that automates the verification of the Helm chart deployment for the UI project. The script ensures that both the frontend and backend components are successfully deployed, running, and accessible.
Fixes #1116 
- ✅ Added `scripts/helm-test.sh` to test Helm chart deployments.
- ✅ Verifies frontend service using port-forward and curl.
- ✅ Verifies backend service using port-forward and health check endpoint.
- ✅ Includes Helm linting, install, pod readiness check, and cleanup (optional).
- ✅ Displays ticks and status for better readability.
```bash
[✅] Frontend responded successfully.
[✅] Backend health endpoint is reachable.
> Add Helm chart test script with frontend & backend verification

- frontend/src/components/Layout.tsx
fix: Extra cruft on expand/contract menu button (#1356)
Also fixed alignment of the menu button 
before : 
after : 
Fixes #<issue_number>#1356
before : 
after :
> fix: remove extra cruft from sidebar toggle button (#1356) + alignment issues with menu button 

- docker-compose.yml
- frontend/Dockerfile
The `docker-compose.yml` file now sets the build context to the project root
Fixes #1442 
- The `docker-compose.yml` file now sets the build context to the project root  and specifies `frontend/Dockerfile` as the Dockerfile path
- Improved commit hash generation In `frontend/Dockerfile`
> Fixed git commit when using docker

- README.md
- Explains how to copy the .env.example file to .env in the backend directory
- Shows the content of the example .env file with all required environment variables
- Includes a note about updating values for local environment setup
Fixes #1447
> FIX: Environment variable setup for backend is missing for Local setup

- backend/k8s/metrics.go
- backend/routes/metrics.go
- frontend/src/components/Clusters.tsx
- frontend/src/hooks/queries/useK8sQueries.ts
This PR addresses a critical bug where CPU and Memory usage in the Resource Utilization dashboard was displaying simulated data instead of actual cluster metrics. The implementation now fetches real-time resource usage from Kubernetes clusters by querying node capacity and pod resource requests, providing accurate monitoring data for capacity planning and cluster health assessment.
Fixes #1465 
> Fix CPU and Memory Usage to Use Real Kubernetes Metrics Instead of Hardcoded Values

- .eslintignore
- frontend/eslint.config.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/login/tokenUtils.ts
- frontend/src/hooks/queries/useLogin.ts
- frontend/src/lib/api.ts
This PR implements frontend support for automatic handling of JWT token expiration and refresh.
- 🕒 Detects when JWT token is expired before sending a request
- 🔁 Automatically refreshes token using `/api/refresh`
- ✅ Retries the original request after successful token refresh
- 🚫 If refresh fails, logs out user and redirects to login
- 🔐 Stores both access and refresh tokens securely
- 📣 Provides clear toast messages on auth-related issues
- 🔧 Fixes TypeScript `any` usage in Axios interceptor
- 🧹 Ignores `coverage/` files from eslint to reduce noise
fixes  #877
> ✨fix(auth): properly type Axios request config for retry logic

- frontend/src/components/CommandPalette.tsx
- frontend/src/locales/strings.en.json
Added a new command to the Command Palette to quickly navigate to the Metrics Dashboard. This improves accessibility and discoverability of performance monitoring features for developers and users.
Fixes #1483
- Type: navigation
- Icon: `FiBarChart2` from `react-icons/fi`
- Action: Navigates to `/metrics`
- Keywords: ["metrics", "dashboard", "monitoring", "performance", "prometheus"]
- Section: navigation
Not applicable — feature tested via Command Palette interaction.
> added Metrics Dashboard command in Command Palette

- frontend/src/components/MetricsDashboard.tsx
- frontend/src/hooks/queries/useMetricsQueries.ts
- frontend/vite.config.ts
This PR fixes a user experience issue in the Metrics Dashboard where auto-refresh preferences were not persisted across page refreshes. Previously, when users disabled auto-refresh and refreshed the page, the setting would automatically re-enable, causing confusion and poor UX. This fix ensures that user preferences for auto-refresh and refresh interval are saved to localStorage and restored on component mount.
Fixes #1474 
[Screencast from 2025-07-13 09-40-49.webm](https://github.com/user-attachments/assets/5a71b7c4-9d3e-48cc-854e-7a0face3d26e)
> Fixes: Persist Metrics Dashboard auto-refresh preferences in localStorage and Removed Hardcoded Prometheus URLs

- frontend/src/pages/InstallationPage.tsx
Fixes a type inconsistency in `InstallationPage.tsx` related to toast dismissal logic.
---
Fixes #1505 
---
---
---
N/A (toast logic + type-only fix)
---
This change eliminates redundant toast notifications on language switch and corrects a TypeScript typing error related to toast IDs.  
The behavior is now clean and matches expected UX across all languages.
If similar toasts are used elsewhere, make sure toast IDs are consistently typed as `string | null` for compatibility with `toast.dismiss()`.
> fix: prevent duplicate toast notifications on language switch (#1505)

- frontend/src/components/WecsDetailsPanel.tsx
This PR implements an "Edit" option for managing cluster labels directly within the Remote Cluster tree view (WecsDetailsPanel).
Users can now edit cluster labels via the YAML/JSON editor, and the frontend will correctly parse and send the full set of labels to the backend, ensuring all labels (existing and new) are preserved after an update.
The UI also refetches cluster details after a successful update, so the latest labels are always displayed.
Fixes #465 
* Added an "Edit" option for cluster labels in the Remote Cluster tree view.
* Refactored handleUpdate in `WecsDetailsPanel.tsx` to:
* Parse the edited manifest (YAML or JSON) on update.
* Extract all labels from metadata.labels.
* Send the full set of labels in the PATCH request to `/api/managedclusters/labels.`
* Show an error if …
> ✨: Added Edit Option for Managing Cluster Labels in Remote Cluster Tree

- backend/api/metrics.go
- backend/k8s/metrics.go
- frontend/src/hooks/queries/useBPQueries.ts
- frontend/src/hooks/queries/useClusterQueries.ts
- frontend/src/hooks/queries/useK8sQueries.ts
- frontend/src/hooks/queries/useWDSQueries.ts
- frontend/src/pages/Dashboard.tsx
This PR addresses several performance bottlenecks that were causing excessive loading times (over 2 minutes) on the dashboard.
Fixes #1470 
---
**Caching:**
- Added caching to `GetClusterMetrics` API endpoint with a 30-second expiration
- Added caching to `GetPodHealthMetrics` API endpoint with a 60-second expiration
**Parallel Processing:**
- Implemented parallel collection of cluster metrics using goroutines
- Implemented parallel pod health checks using goroutines
**Concurrency Control:**
- Introduced semaphores to limit concurrent API calls to 5
---
**Lazy Loading:**
- Enabled lazy loading for heavy components like `ClusterDetailDialog`
**React Query Optimization:**
- Set appropriate `staleTime` and `cacheTime` for all query hooks
- Updated all query hooks to accept configuration …
> Fix: Dashboard Loading Delay (2+ Minutes to 5 sec)

- frontend/src/pages/ResourceFilterPage.tsx
This PR improves the user experience and security of the Resource Explorer by filtering out Kubernetes system namespaces from the Namespace dropdown. Only user-created namespaces and the `default` namespace are now displayed, making it easier for users to focus on their own resources and reducing clutter in the UI.
- System namespaces filtered out: any namespace starting with `kube-` (e.g., `kube-system`, `kube-public`, `kube-node-lease`).
- The dropdown now only shows relevant namespaces for resource filtering and selection.
Fixes : #1521 
**Screenshot:**
[Screencast from 2025-07-16 22-02-08.webm](https://github.com/user-attachments/assets/4dba9333-89a6-4411-a202-ea778efd092d)
> Filter Out System Namespaces from Resource Explorer Namespace Dropdown

- frontend/src/components/DetachmentLogsDialog.tsx
- frontend/src/components/ListViewComponent.tsx
- frontend/src/components/OnboardingLogsDisplay.tsx
- frontend/src/components/WecsDetailsPanel.tsx
- frontend/src/context/WebSocketProvider.tsx
- frontend/src/hooks/queries/useWebSocketQuery.ts
This PR attempts to mitigate a potential memory leak in the KS UI, as described in #1491
Users reported that leaving the UI running over the weekend slowed down the entire system, possibly due to unclosed connections or background processes.  
These changes aim to reduce resource usage when the UI is idle or unmounted.
---
#1491 
---
---
---
N/A
---
While these changes do not guarantee a full resolution, they significantly improve cleanup of background connections and timers.  
I welcome feedback or suggestions in case there are better approaches to reduce idle memory usage.
> Partial Fix: Reduce Memory Usage and Lag by Cleaning Up Idle Resources

- backend/test/wecs/exec_test.go
- backend/test/wecs/wecs_test.go
- backend/wecs/exec.go
* Added and improved tests for `backend/wecs/exec.go` and `wecs.go` (including concurrency, shell validation, and struct checks).
* Exported `IsValidShellCmd` and `GenTerminalSessionId` so they can be tested.
* Fixed a panic in `SessionMap.Close` by adding a nil check for the socket
Fixes #1526 
None.
> ✨ Feature: Added Unit test for `Wecs` Package.

- frontend/src/components/wecs_details/tabs/EditTab.tsx
- Ensures the deployment configuration is displayed in the correct format (YAML or JSON) immediately when editing a workload.
- Adds a `useEffect` to convert and normalize the manifest content based on the selected editor mode on first load and when switching formats.
- Resolves issue where YAML mode would initially show JSON until toggled.
Fixes #1613 
Before : 
[Screencast from 2025-07-23 20-22-20.webm](https://github.com/user-attachments/assets/006e581f-4c8f-4ca1-9a28-5cef265b83c2)
After : 
[Screencast from 2025-07-23 20-41-44.webm](https://github.com/user-attachments/assets/136532e2-b964-4038-adef-c2dbdeb1afa8)
> Fixes: Ensure EditTab renders manifest in correct format on initial load

- README.md
Updated our slack channel "kubestellar-dev" from the kubernetes to the cncf slack organization.
Fixes #1628
> Fixes: Updating - moving from kubernetes slack org to cncf slack org

- frontend/src/pages/Dashboard.tsx
Fix the current context card ui to handle big text names.
#1634 
Fixes #1634 
- Added truncate attribute to the `<h3>` tag which is responsible for current context name rendering. This is a Tailwind CSS utility that automatically adds multiple dots at the end to any text that is too long to fit within the component.
- Added  min-w-0 attribute to the container div around the text. This is a minor flexbox fix. It prevents the long text from meshing with other components around it.
Before : 
After:
> FIX : currentContext card to hold big names.

- frontend/src/components/TreeViewComponent.tsx
- frontend/src/components/treeView/NodeDetailsPanel.tsx
- frontend/src/components/treeView/hooks/useTreeViewActions.ts
Fixed the context menu actions (Details, Edit, Logs) in staged workloads that were not working properly. The issue was that the `useTreeViewActions` hook wasn't properly connected to handle menu actions, causing the three buttons to be non-functional.
Fixes #1621 
https://github.com/user-attachments/assets/c9c91832-04c3-4622-bf64-2ba41d131976
This fix ensures consistent behavior between staged and deployed workloads for the three-button context menu functionality.
> Fix: Context menu actions not working in staged workloads

- frontend/src/components/wds_topology/ZoomControls.tsx
- frontend/src/locales/strings.en.json
Fixes #1633 
Before:
After:
[Screencast from 2025-07-25 15-39-47.webm](https://github.com/user-attachments/assets/d7382aef-84c0-48c6-a1a9-51ddf29f9714)
> Feat : Toggle Button for curvy/square Edge with awesome UI/UX

- CONTRIBUTING.md
This PR enhances the contribution documentation by adding a new section titled **"Contribution Commands Guide"**. It explains how contributors can:
- Assign/unassign themselves to issues using `/assign` and `/unassign` comments.
- Automatically request labels like `help wanted` and `good first issue` using `/help-wanted` and `/good-first-issue` comments.
> Update Contribution Guide with Comment-Based Commands

- frontend/src/components/ResourceFilters.tsx
This PR fixes the visual "zoom-in" effect that occurred when selecting or deselecting filters in the `FlowCanvas.tsx` view. The issue was caused by unstable layout dimensions and dynamic width calculations in the filter UI, which led to layout reflows and perceived zooming.
The solution involved:
- Removing dynamic width handling and ref-based sizing from the filter components
- Ensuring fixed container dimensions and consistent spacing/margins
- Using `position: fixed` for dropdown menus to avoid layout interference
- Stabilizing flex layouts and applying `flex-wrap` where necessary
- Making the active filters section layout-stable, even when hidden
These changes collectively ensure that the page remains stable and does not visually jump or shift during filter interactions.
---
Fixes …
> Fixes Page Zoom-In Effect When Selecting Filters

- frontend/src/components/LanguageSwitcher.tsx
This PR fixes a bug where the bubble icon on the translation button was not displaying the correct language code for Simplified and Traditional Chinese.
Fixes #1699
- Updated the language codes for Simplified and Traditional Chinese in `frontend/src/components/LanguageSwitcher.tsx` from `zh-Hans` and `zh-Hant` to `SC` and `TC` respectively.
**Before:**
[
**After:**
This change aligns the displayed language codes with the expected behavior, improving the user experience for Chinese-speaking users.
> fix(i18n): Correct language codes for Chinese translations

- frontend/src/pages/InstallationPage.tsx
http://localhost:5173/install
after hovering the violet color is not visible with blue backgroud color
there should be margin top above "Installation Instructions" and "kubectl is correctly installed and meets the version requirements."
Fixes #1729
after hovering the violet color is not visible with blue backgroud color
https://github.com/user-attachments/assets/9bc44fdc-57a2-4e10-adf4-963e53debb71
https://github.com/user-attachments/assets/defcd95d-f214-4d72-a37e-6897bd9c7b2c
there should be margin top above "Installation Instructions" and "kubectl is correctly installed and meets the version requirements."
https://github.com/user-attachments/assets/cff447ec-bddf-4d6b-a929-a46f12e2ba64
https://github.com/user-attachments/assets/b226dbca-a716-454b-a38d-1e71b0eac91e …
> Minor Bugs in Installation Page

- frontend/src/locales/strings.en.json
Updated workload label to Resources
Fixes #1740 
> Update workload label to 'Resources' in English localization strings

- frontend/src/hooks/useBackendHealthCheck.ts
I have changed the api endpoint call from '/api/health' to '/health' from the useBackendHealthCheck.ts, which was causing error ,  as @btwshivam said me that we are not using api/health endpoint so , changed the frontend call and not updated the backend route
Fixes #1620  #1704 
> Refactor backend health check API endpoint in useBackendHealthCheck hook

- README.md
Added the missing `.env` variable in the documentation for better clarity of new contributors
Fixes #1751
> Added the missing .env variable to `README.md`

- backend/api/marketplace.go
- backend/marketplace/manager.go
- backend/marketplace/storage.go
I have updated the result of `GetMarketplacePluginCategoriesHandler()`, which previously returned a nil result in some cases and caused the error of no marketplace plugin found when open the Marketplace page.
Fixes #1836
> refactor: update marketplace's tags fetching result

- frontend/src/pages/ResourceFilterPage.tsx
[Screencast From 2025-08-19 19-31-11.webm](https://github.com/user-attachments/assets/28bdf0be-5814-437d-9b59-62e227eaacfa)
Fixed #1831
> fix: alphabetically sort object type dropdown in resource explore

- frontend/src/pages/InstallationPage.tsx
This PR fixes the **navbar margin issue** on the Installation Page.  
The navbar previously had unnecessary margins on the left and right, which caused inconsistency compared to the main dashboard page. 
My branch was up-to date with yours, moreover I only pushed the changed file so there wont be any issue of merge.
**Changes Made**
- Set navbar container `width:  full`
- Removed unnecessary left/right margins
- Ensured styling is consistent with the main dashboard
**Before:**  
Unnecessary margin on both sides  
**After:**  
Fixed navbar, now spans full width  
**🔗 Related Issue**
Closes #1718
> Fix: Navbar width set to full in Installtion Page

- frontend/src/components/marketplace/PluginDetails.tsx
- The entire table row that displayed platform information ("Platforms: Linux, macOS, Windows")
- This was located in the "Requirements" section of the technical details tab
- The removal was clean and doesn't affect the surrounding code structure
> Removed Platform from plugin details

- frontend/src/components/marketplace/CategoryFilter.tsx
- frontend/src/pages/GalaxyMarketplace.tsx
- Resolves the issue where the marketplace heading overflows with the navbar.
- Improves the UI and z-index handling for the marketplace header and category filter.
- Only changes GalaxyMarketplace.tsx and CategoryFilter.tsx.
Fixes #1877 
https://github.com/user-attachments/assets/70c3ec0b-72c5-40e3-a623-af728325b1f9
Marketplace heading no longer overflow with Navbar
> fix: resolve marketplace heading overflow with navbar

- frontend/src/components/Layout.tsx
- Fix the laggy sidebar expand/collapse menu transitions.
- Fixes #1949 
- Slow transition duration (0.25s)
- Basic easing ('easeInOut')
- Missing GPU acceleration properties
Before:
https://github.com/user-attachments/assets/53d78c1e-bd27-47a9-a378-1274991643d3
After:
https://github.com/user-attachments/assets/7feacae8-571d-43e1-bea9-ed4f439b7583
> Fix the laggy sidebar expand/collapse menu transitions

- frontend/src/components/wds_topology/ZoomControls.tsx
This PR introduces a collapse/expand toggle button for the controls panel located beside the zoom controls.
Fixes #1801 
https://github.com/user-attachments/assets/37e41e98-74a7-4621-bb83-86199bab0b11
> feat(ui): add collapse/expand button to toggle additional controls

- frontend/src/lib/api.ts
I adjusted the condition for displaying the warning relating to JWT Token on the Login page (to not show the warning).
Fixes #2037
https://github.com/user-attachments/assets/ce976b0a-c801-40ff-a013-75e9ba1d51bd
To test this change, you can temporarily set the expiration time for the JWT Token to 10 seconds instead of 24 hours.
File: `backend/utils/jwt.go`
> refactor: update the condition for displaying the invalid token

- frontend/src/components/ResourceCard.tsx
- frontend/src/components/ResourcePreview.tsx
- frontend/src/locales/strings.en.json
ResourcePreview.tsx:
Added [useTranslation](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) import
Internationalized:
"Object Details" → [t('resources.preview.objectDetails')](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
"Namespace:" → [t('resources.preview.namespace')](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
"Created:" → [t('resources.preview.created')](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
"UID:" → [t('resources.preview.uid')](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench …
> Internationalized all hardcoded strings from the Object Explorer components

- backend/main.go
In this PR, I truncated the Bearer Token being printed out in the backend log.
Fixes #2044
> chore: truncate Bearer Token in backend logged http request

- backend/api/metrics.go
- backend/monitoring/prometheus/prometheus.yml/config.yml
- monitoring/prometheus.yml
- Updated Prometheus configurations in both:
- [prometheus.yml](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
- [config.yml](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
1. Prometheus can successfully scrape metrics from /api/v1/metrics
2. The endpoint returns proper Prometheus-formatted metrics via [api.GetRawMetrics](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
3. No more 400 errors will occur during metrics collection
> Fix: Prometheus can now successfully scrape metrics from /api/v1/metrics
