kubestellar/ui

backend/main.go

I have added a simple debug line to the KubestellarUI codebase to test the PR functionality and ensure that I am able to contribute successfully to the repository.

Added debug log to KubestellarUI at the line 39

---

backend/main.go

Added logging to track kubeconfig file path

feat: added debug for kubeconfig path

---

src/pages/ITS.tsx

Fixes : #6 
- Fixed the `useEffect` dependency array to prevent infinite API requests.
- Optimized state updates to avoid redundant renders.

Fix : Infinite API calls to /api/clusters

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Fixes #14 
Added ISSUE_TEMPLATE and PR templates for keeping the consistent contribution.

Added issue and pr templates

---

.github/workflows/add-contributor.yml
README.md

Similar to this but it can add automatically

feat: add contributor to readme.md file

---

package-lock.json
package.json
src/components/Navbar.tsx
src/context/ClientThemeWrapper.tsx
src/context/ThemeContext.tsx
src/hooks/useChangeTheme.ts
src/main.tsx

[Screencast from 24-01-25 11:01:59 AM IST.webm](https://github.com/user-attachments/assets/da86af5b-8d2a-43c2-b5c6-4741f401ce69)

added change theme toggle button

---

README.md

Enhance the README by adding setup instructions for Kubernetes clusters and Docker Compose, improving clarity and usability for users.

Update README with Kubernetes and Docker Compose instructions

---

README.md
backend/api/handlers.go
backend/main.go
backend/models/cluster.go
backend/services/clusterService.go
backend/utils/utils.go
src/context/ThemeContext.tsx
src/context/ThemeProvider.tsx
src/main.tsx
src/pages/ITS.tsx

This PR implements cluster onboarding using the `kubeconfig` for seamless integration and management of clusters. It also refactors the folder structure to improve maintainability and scalability of the project.
ref : #36 

[Demo] :  Cluster onboarding using KubeConfig

---

.github/workflows/size-limit.yml
.gitignore
package-lock.json
package.json
vite.config.ts

Fixes #8
`npm run build`
`npm run size-limit`

feat: added ci for size-limit and bundle size analyser locally

---

.github/dependabot.yml
README.md

This PR adds a Dependabot configuration file to automate dependency updates for both **React (npm)** and **Gin (Go)**. It ensures our dependencies remain up-to-date and secure by creating automated pull requests.
Fixes #40 
N/A
After merging this PR, Dependabot can be enabled in **Settings → Security & analysis** to start automating dependency updates.

Dependency manage bot

---

.github/dependabot.yml

package-ecosystem fixes 
A little fix for the bot 

[Fixes] : go fixes for the bot

---

Dockerfile
backend/Dockerfile
docker-compose.yml

Enhance the Docker build process for both frontend and backend applications, optimizing dependency installation and environment setup. Update docker-compose to streamline service dependencies and configuration.

Refactor Dockerfiles and docker-compose for improved build process and environment configuration

---

backend/main.go

feat: added status for k8s deployment

---

src/pages/ITS.tsx

I added and aligned checkboxes to appear on clusters table so users can select them.
Fixes #63 
Going to need add a checkbox to the left of the searchbar as a "Select All" option

Added checkboxes for each cluster on table

---

src/pages/ITS.tsx

Moved Select All checkbox into the table
N/A

Put Select All checkbox in table

---

src/pages/WDS.tsx

Enhance code readability and utilize `API_BASE_URL` for constructing dynamic endpoints in the WDS component.
Fixes #72

Refactor WDS for improved readability and dynamic API endpoint

---

src/pages/ITS.tsx

Added an icon for Cluster Size. I also updated the Status icon.
N/A

Added Cluster Size icon and updated Status icon

---

src/pages/ITS.tsx

Added page buttons to the table
Had to drop the border for the table. The table will look more obvious if we can change the background color. And still need to add functionality to the page buttons.

Add page buttons

---

backend/github/fetchYamlFile.go
backend/main.go

https://github.com/user-attachments/assets/40c89985-dc24-47b2-8f49-31d2627acb03

feat: added functionality to fetch yaml file from github repo and create Deployment

---

.github/workflows/ci.yml

**Title:** ✅ Add GitHub Actions CI for Frontend & Backend with Test Pass Indicators  
This PR enhances the GitHub Actions CI pipeline by:  
- Running checks for both the frontend and backend on every push and PR.  
- Adding test, build, and formatting validation for Node.js and Go.  
- Displaying ✅ success messages when each step completes successfully.  
- Ensuring formatting checks fail if Go files are not formatted properly.  
*** Fixes #81 
**Changes:**  
- Added `npm ci`, `npm lint`, `npm test`, and `npm build` for the frontend.  
- Added `go mod download`, `gofmt` check, and `go build` for the backend.  
- Included success messages for improved CI visibility.  
**Testing:**  
- Verified that the CI runs successfully for both frontend and backend.  
- Ensured that …

 Add GitHub Actions CI for Frontend & Backend with Test Pass Indicators  

---

.github/workflows/greeting.yml

Improve the greeting messages for new contributors in the GitHub Actions workflow and refine permissions for better access control.
Fixes #87

Enhance greeting messages for new contributors and adjust permissions in GitHub Actions workflow

---

src/components/Clusters.tsx
src/components/Header.tsx

This PR refines the cluster filtering logic to ensure only Kubeflex-related resources are displayed. It also improves the UI by simplifying the header and optimizing the cluster selection process.
Fixes #78 
- [Header UI Improvements: Removed redundant cluster view selector.
-Cluster Selection Dropdown: Now focuses only on Kubeflex contexts.
- Performance Enhancements: Optimized data filtering on initial load

Kubeflex Cluster Filter Implementation

---

src/pages/ITS.tsx

Bug fixes for ITS page
Fixes #77 

ITS page bug fixes  for showing clusters info

---

src/pages/NotFoundPage.tsx

slow them rockets down

---

backend/go.mod
backend/go.sum
backend/main.go
backend/wds/deployment/common.go
backend/wds/deployment/logs.go
src/components/Logs.tsx
src/routes/routes-config.tsx

Fixes https://github.com/kubestellar/ui/issues/79
Fixes https://github.com/kubestellar/ui/issues/101
https://github.com/user-attachments/assets/016161b0-e01b-472c-be43-38c736ff4f04

feat: added minimal real time deployment logs by websocket

---

Dockerfile
nginx.conf

Introduce a custom Nginx configuration to serve the frontend and proxy API requests to the backend.
Fixes #76

Add custom Nginx configuration for frontend and API proxying

---

backend/main.go

its default context set for /api/clusters endpoint
Fixes #77 

ITS default context set for /api/clusters endpoint

---

src/pages/NotFoundPage.tsx

This pull request addresses removes the 404 text from NotFoundPage.tsx
Fixes #115 
- This PR removes the h1 tag containing 404 text from the NotFoundPage.tsx

removed 404 text from 404 page

---

src/pages/NotFoundPage.tsx

added shift of logo on 404

---

.dockerignore
Dockerfile
example.env

Improve the Docker setup to include the Git commit hash and application versioning, facilitating better tracking of builds.
Fixes #131

Enhance Docker setup with Git commit hash and versioning

---

.gitignore
backend/go.mod
package-lock.json
package.json
src/components/CreateOptions.tsx
src/components/DeploymentDetails.tsx
src/components/DeploymentTable.tsx
src/components/LogModal.tsx
src/pages/WDS.tsx
tailwind.config.js

This PR introduces a new Create Workload feature in WDS, allowing users to visualize the deployment status, edit a selected deployment, scale a deployment, and delete a deployment.
Related Issue
Partially addresses https://github.com/kubestellar/ui/issues/51
Visualize the deployment status
Edit a selected deployment ui,
Scale a deployment ui,
Delete a deployment.
This enhancement improves user control over deployments, making it easier to manage workloads efficiently.

new features to wds-frontend

---

src/pages/BP.tsx

This PR enhances the KubeStellar Binding Policy interface to provide better visibility and control over policy matching between clusters and workloads.
Partially addresses #54 
- Implemented a new dynamic preview system that shows real-time matches between clusters and workloads based on label selectors
- Rebuilt the UI using Material-UI components while maintaining the existing layout and user experience

Enhanced Binding Policy UI with Dynamic Preview

---

backend/main.go
src/components/ClustersTable.tsx
src/pages/ITS.tsx

Updated its page to show contexts and also updated apis to show the contexts for each clusters

ITS context were shown on UI after modification on backend  apis

---

src/pages/BP.tsx

This PR adds complete CRUD functionality for managing policies in the  UI. The implementation includes form-based creation and editing, a confirmation dialog for deletion, and enhancements such as label management, status handling, and form validation. The data is currently managed in the component's state and can be easily integrated with backend APIs in the future by updating the handler functions.
Partially addresses #54 
- Create Functionality: Added a form to create new policies
- Update Functionality: Implemented an edit form to modify existing policies.
- Delete Functionality: Added a confirmation dialog before deleting policies.
- Form Validation: Ensured input validation for required fields.

 Add CRUD functionality with form validation 

---

src/index.css

This PR removes an unintended horizontal scrollbar for better user experience. 
Fixes #146 
- Removed min-width and overflow property from index.css file to remove the horizontal scrollbar.

Fix: Remove Unnecessary Horizontal Scrollbar

---

src/pages/BP.tsx

Fixed the search functionality for the Binding Policy.
Fixes #155 
- Added Search State:
- Implemented Filtering Logic
- Updated Pagination Text

Fixed the search functionality for Binding Policy

---

src/components/ClustersTable.tsx

Fixed poor visibility of text elements in dark mode for the Clusters Table component:
- Search input label and text
- Filter dropdown label and selected text
- Maintained consistent white text color
- Preserved Material-UI focus states (blue)
- Added proper text color styling for dark mode in TextField
- Fixed Filter dropdown label and selected text colors
- Maintained consistent white color scheme
- Kept default Material-UI focus behaviors
Fixes #169

fix: Improve text visibility in dark mode

---

src/components/menu/data.ts

Removing the Kubeconfig Onboard from the Navbar since it won't be used anymore. Instead, I'll be creating an Onboarding table similar to `DeploymentTable.tsx` for the cluster creation.
Fixes #170 
I will delete `KubeconfigOnboarding.tsx` once I created the kubeconfig creation option on the onboarding table

Removed Kubeconfig Onboard from Navbar

---

backend/api/deploy.go
backend/k8s/client.go
backend/k8s/deployer.go
backend/main.go

Gitops : Fetch manifest files from github and deploy it

Gitops : Fetch manifest files from github and deploy it 

---

backend/main.go
backend/wds/controller.go
backend/wds/deployment/logs.go

Fixes #145
* implemented logs for specific deployment using NewSharedInformerFactoryWithOptions
* Implemented logs for all wds deployment using SharedInformerFactory
https://github.com/user-attachments/assets/851d2b2b-d268-4894-a15a-dbe8b501b3cc

feat: implemented informer for deployment workload using SharedInformerFactory

---

backend/k8s/client.go

Improve the Kubernetes client setup by allowing the use of a custom kubeconfig file and specifying the context to be used, enhancing flexibility for users.

Enhance Kubernetes client configuration for custom kubeconfig and context

---

src/components/menu/data.ts

Fixed and updated the menu. Got rid of "Onboard." Renamed "Overview" to "Managed"
Should we keep it as "Managed" or change it to "Manager"?

Fixed Menu, got rid of Onboard and renamed Overview to Manage

---

src/components/ClustersTable.tsx

**Bug Fixes**
1. Search Query Trimming: Trimmed whitespace from search queries to ensure accurate filtering.
2. Fixed the filter functionality.
3. Status Filter Handling: Defaulted undefined status values to `'Active✓'` for consistency.
4. Filtering Logic Improvement: Search now considers the `context` property, making it more comprehensive.
**New Features & Enhancements**
1. Expanded search to include the `context` property along with `name` and `labels`.
2. Status badges now adapt dynamically (red for inactive, yellow for pending, green for active).
3. Enhanced Button & Pagination Styling: Improved UI with better theme support, hover effects, and clearly defined disabled states.
4. Fixed inconsistencies for a seamless light/dark mode experience.
5. Refactored filtering logic and …

Bug Fixes & Enhancements in ClustersTable

---

src/components/BindingPolicy/BPTable.tsx
src/components/BindingPolicy/PolicyVisualization.tsx
src/components/BindingPolicy/PreviewDialog.tsx
src/pages/BP.tsx

This PR improves the binding policy preview functionality by adding a dedicated visualization tab and enhancing the preview dialog UI. The preview action has been moved from the table header to individual policy rows, allowing  to preview specific policies. The changes include a new tabbed interface with visualization and detailed views for better policy insights.
Partially addresses: #54 
- Moved preview action from table header to individual policy rows
- Added tabbed interface in PreviewDialog with Visualization and Details views
- Updated onPreviewMatches to accept specific policy parameter
-Integrated PolicyVisualization component for better policy insights

feat(binding-policy): enhance preview functionality with visualization

---

src/components/BindingPolicy/Dialogs/EditBindingPolicyDialog.tsx
src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
src/components/BindingPolicy/PolicyVisualization.tsx
src/components/BindingPolicy/PreviewDialog.tsx

This PR enhances dark mode styling across all Binding Policy-related dialogs and components, ensuring visual consistency, better readability, and improved user experience in dark theme mode.
- Applied consistent dark mode color scheme.
- Improved contrast ratios for better readability.
- Updated background colors using the slate palette for a modern UI.
- Enhanced visual hierarchy to maintain clarity in dark mode.
- Adjusted text colors to ensure proper visibility.
- Implemented uniform dark mode styling.
- Updated dialog backgrounds to match the theme.
- Improved text contrast for accessibility.
- Enhanced tab styling for better navigation.
- Optimized integration with visualization components.
- Enabled full dark mode support for dialog content.
- Updated Paper components with proper …

Dark Mode Consistency Improvements Across Binding Policy Components #201

---

src/components/BindingPolicy/Dialogs/DeleteDialog.tsx
src/components/BindingPolicy/Dialogs/EditBindingPolicyDialog.tsx
src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
src/components/BindingPolicy/PreviewDialog.tsx
src/components/CreateBindingPolicyDialog.tsx
src/components/CreateOptions.tsx
src/components/ImportClusters.tsx

**This PR addresses issues with modal dialog behavior and styling across the application, focusing on consistency, stability, and user experience.**
**1. Fixed Dialog Positioning and Sizing**
- Implemented fixed height (80vh) for all dialogs
- Added consistent margins (2 units) from screen edges
- Prevented unexpected resizing and jumping during interactions
**2. Improved Layout Structure**
- Added proper flex layout system
- Fixed content scrolling behavior
- Implemented stable headers and footers
- Prevented double scrollbars
**3. Enhanced Visual Styling**
- Added consistent border treatments
- Improved tab styling and indicators
- Enhanced visual separation between sections
- Added hover states for better interactivity
**4. Theme Integration**
- Better dark/light theme support
- …

Fix: Modal Dialogs Styling and Behavior & Border issue

---

README.md
backend/go.mod
backend/go.sum
backend/namespace/namespace.go
backend/redis/redis.go
docker-compose.yml

Implement Redis caching to optimize namespace data retrieval, reducing the frequency of Kubernetes API calls. Update Docker configuration to include a Redis service.
Fixes #212

Integrate Redis caching for namespace data retrieval

---

src/components/BindingPolicy/BPPagination.tsx
src/components/ClustersTable.tsx
src/components/ImportClusters.tsx
src/pages/BP.tsx

gestions, or questions related to this PR. -->

fixed  pagination in Bp and disabled buttons

---

src/components/menu/Menu.tsx
src/components/menu/MenuItem.tsx
src/components/menu/data.ts

The previous menu was outdated, lacked modern styling, and had usability issues. This update improves its structure, accessibility, and design for a smoother and more intuitive user experience.
- Reorganized sections for better hierarchy and clarity:
- Main: Home, Profile
- Management: Clusters, Deployments, Workloads
- Binding Policies: Overview, Manage Policies.
- Improved overall navigation for a more intuitive user flow.
- Added proper scroll containment using `max-h-[calc(100vh-6rem)]`.
- Implemented custom scrollbar styling with:
- Backdrop blur effect.
- Refined border styling for a sleek, modern look.
- Added `ARIA` attributes for better screen reader compatibility.
- Improved tooltip handling for disabled states.
- Enhanced visual feedback for active and disabled menu items.
- …

Modernizing the Menu: UI/UX Enhancements & Code Cleanup

---

backend/main.go
backend/wds/bp/handlers.go

Adde the getAllbp function to get all the binding policy. Also added, improved error handling, and adds detailed logging.
Fixes #222 
- Added new GetAllBp function to retrieve and filter BindingPolicy resources.
- Enhanced validation in CreateBp with better YAML parsing and metadata checks.
- Improved error messages with more descriptive information.
- Enhanced response structures with additional context and details.

Added get endpoint for BindingPolicy

---

src/components/ClustersTable.tsx

fix: All-Filter

---

src/components/CreateOptions.tsx
src/components/DeploymentTable.tsx
src/components/ImportClusters.tsx
src/components/LogModal.tsx
src/lib/api.ts
src/pages/NS.tsx
src/utils/credentials.ts

I have removed all the hardcoded API's that were present in the code.
Fixes #137 
I have removed all hardcoded API's with a variable named BASE_URL 

Fix: replaced all hardcoded apis

---

backend/api/deploy.go
backend/k8s/deployer.go
backend/main.go
backend/namespace/namespace.go
backend/redis/redis.go

Implement GitHub webhook processing and integrate Redis for managing deployment configurations, including storing repository URLs and folder paths for auto-deployments.
Fixes #242
part of #50

Add GitHub webhook handling and Redis integration for deployment management

---

backend/main.go
backend/wds/bp/handlers.go
src/components/BindingPolicy/BPTable.tsx
src/components/BindingPolicy/Dialogs/BPHeader.tsx
src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
src/components/CreateBindingPolicyDialog.tsx
src/pages/BP.tsx
src/types/bindingPolicy.ts

Enhance the functionality and user interface of the Binding Policy (BP) management system. Key updates include the addition of a new API endpoint for retrieving BP status, improvements in the UI components for better user interaction, and enhancements in the data handling logic to support new features.
Fixes #239 
- Added a new GET route /api/bp/status to retrieve the status of a specific Binding Policy.
- Implemented the GetBpStatus function to handle requests for BP status, including logic to determine the active status based on conditions.
- Updated the table component to display BP status with color-coded chips and icons for better visual representation.
- Integrated the new BP status API call to fetch and display status information for each policy.
Please ensure the following before …

 Enhance BP status management with new API and UI integration

---

src/components/ImportClusters.tsx

fix: import cluster borders

---

CONTRIBUTING.md
docker-compose.yml

Fix docker file and updated the docs for setup

fix: update PostgreSQL credentials and database name in documentation

---

CONTRIBUTING.md
backend/Dockerfile
docker-compose.yml

Update PostgreSQL User Configuration and Introduce JWT Secret Generation for Enhanced Security  
---
This PR enhances the security and configuration of the PostgreSQL setup and JWT authentication by:  
✅ Updating the PostgreSQL user configuration in both **documentation** and **Docker setup**.  
✅ Introducing automatic JWT secret key generation inside the container for improved security.  
🔹 **PostgreSQL Configuration:**  
- Updated the **PostgreSQL user setup** in the `Dockerfile` and relevant scripts.  
- Ensured the database user follows best security practices.  
- Modified documentation to reflect the latest database setup.  
🔹 **JWT Secret Generation:**  
- Automatically generates a secure **JWT secret key** during container startup.  
- Stores the generated key securely for …

Update PostgreSQL User Configuration and Introduce JWT Secret Generation for Enhanced Security  

---

backend/routes/bp.go
backend/routes/setup.go
backend/wds/bp/handlers.go
backend/wds/bp/utils.go

This PR adds update BP method , Now the backend supports editing BPs.
Fixes #218 

support for Updating Binding policies

---

backend/main.go
src/routes/routes-config.tsx

Remove the ProtectedRoute wrapper from routes and disable database connections to streamline the application flow.
Fixes #291

Refactor routes and disable database connections

---

src/components/ClustersTable.tsx
src/components/ImportClusters.tsx
src/hooks/useCSRStatus.ts
src/utils/CSRStatusManager.ts

Added a CSR (Certificate Signing Request) status tracking and management to improve the cluster approval workflow. Needed a structured way to track CSR approvals across different parts of the UI. Using a custom hook allows for cleaner component logic and reusability. The new utility file `(CSRStatusManager.ts)` keeps CSR-related logic centralized, reducing duplication. Improves maintainability and scalability of the cluster approval process.
- Provides reusable logic for fetching and managing CSR statuses.
- Ensures a cleaner separation of concerns by handling CSR state updates outside UI components.
- Centralized CSR-related logic to make future maintenance easier.
- Helps avoid redundant logic in multiple components.
- Integrated CSR status handling for better visibility of approval …

Feat: Added CSR status manager and hook for polling CSR approval

---

src/components/ImportClusters.tsx

- Connected frontend UI with backend API for Import Cluster command generation.
- Fixed API request format and ensured valid cluster names are passed.
- Successfully tested API responses and displayed the generated command in the UI.
https://github.com/user-attachments/assets/008cb7e7-1d39-4ce9-b641-9d5e06b7963a
Will go back to working on CSR

Integrated Import Cluster API and connected frontend with backend

---

backend/its/manual/handlers/cluster.go
backend/its/manual/handlers/command.go
backend/its/manual/utils/utils.go
backend/routes/cluster.go

Cluster available api which displays cluster which are not in ITS and not having context having like *_kubeflex.

cluster-available api added

---

backend/its/manual/handlers/command.go

Correct command response is now send to frontend from generatecommand api which enables user run cluster adma join command. we just have to append clustername in FE

correct command response send to frontend [clusteradam command ]

---

src/components/Header.tsx
src/hooks/queries/useClusterQueries.ts
src/hooks/queries/useHeaderQueries.ts
src/hooks/queries/useK8sQueries.ts

**Changed `/api/clusters//managed`**

Fixed Cluster Endpoints in the Frontend

---

backend/wds/bp/handlers.go
src/pages/BP.tsx

Fixed YAML parsing issues in CreateBp function to improve error handling, add default values for empty fields, and prevent API errors. This enhances the reliability of binding policy creation through the UI. Also added the case to handle the emptystate in UI when no binding Policy is there.
Fixes #305 
- Added default value "core" for empty APIGroup fields
-Set default namespace when downsync namespaces array is empty
- Implemented two-phase YAML parsing for more robust error handling
- Added verification of critical fields after unmarshaling
- Fixed type assertions to handle YAML parsing edge cases

 improve YAML parsing and field validation in binding policy creation

---

backend/namespace/namespace.go
backend/namespace/resources/service.go

This PR enhances namespace resource retrieval by utilizing a dynamic client for better resource discovery and management. This change improves the efficiency of fetching resources associated with namespaces, enabling smoother and faster resource discovery.  
Closes #307 
- Implemented a dynamic client for namespace resource retrieval.  
- Improved resource discovery and management for namespaces.  
- Optimized performance by reducing the overhead of manual resource fetching.  
- Refactored relevant code sections to integrate the dynamic client.  
- Added error handling and fallback mechanisms for failed resource fetches.  
1. Deploy the updated service with dynamic client integration.  
2. Verify that namespace resources are discovered and managed efficiently.  
3. Test with different …

Refactor namespace handling to use dynamic client for resource discovery

---

src/components/Header.tsx
src/hooks/queries/useClusterQueries.ts
src/hooks/queries/useHeaderQueries.ts
src/hooks/queries/useK8sQueries.ts

Fixed clusters endpoint from `api/clusters/managed` to `api/clusters`

Fix:clusters-endpoint

---

src/components/ImportClusters.tsx

fixes the error toast appearance when opening import cluster dialogue

🌴  Fixes the error toast appearance when opening import cluster dialogue

---

src/components/ImportClusters.tsx

**This PR improves the user experience of the Import Clusters component, with a focus on enhancing the manual option dialog and fixing text visibility issues in dark mode. The changes make the interface more intuitive, visually appealing, and functional across all color themes.**
- Added a clear step-by-step visual guide with numbered steps
- Improved information hierarchy with better section organization
- Added a dedicated "Next steps" section after command generation
- Enhanced command display area with better styling and a floating copy button
- Improved input field styling with descriptive placeholder and helpful tips
- Fixed text input color in dark mode for both manual and API/URL options
- Ensured proper contrast for input labels and text fields
- Added proper styling for focused …

Enhance Import Clusters UI, Fix Dark Mode Text Visibility and Table Bug fixes

---

backend/api/deploy.go
backend/k8s/deployer.go

This PR introduces a **dry-run strategy** that allows executing deployments in a simulated mode without making actual changes. This helps in validating deployment workflows safely.
- Added `dryRun` parameter to API endpoints.
- Implemented logic to simulate deployments without applying changes.
- Updated logs to clearly indicate dry-run executions.
- Added unit tests for dry-run functionality.
- Validated dry-run behavior using Postman.
1. Run the deployment process with `dryRun=true` and verify:
- No actual changes are made.
- Logs clearly indicate **dry-run execution**.
- API responses simulate the deployment output.
2. Test via Postman:
- Send API requests with `dryRun=true` and validate responses.
3. Verify CI/CD pipeline behavior:
- Ensure dry-run mode executes properly without …

Implement Dry-Run Strategy

---

backend/its/manual/handlers/command.go
backend/its/manual/handlers/csr_watcher.go
backend/routes/cluster.go

👀 : CSR Watcher API 

---

backend/k8s/resources.go
backend/routes/resources.go

added list route for all the workload resource

---

backend/k8s/resources.go

I am doing this using the hardcoded way , so I added one logic for it to check is this resource is namespaced or non-namespaced resources
Part of #52 

fix: improved logic for namespaced and non-namespaced resources

---

src/components/ImportClusters.tsx

**This PR introduces multiple UI/UX improvements, enhanced error handling, and design consistency refinements to ensure a seamless user experience across the application.**
- Implemented structured error detection for different HTTP status codes:
- 500: Internal Server Error
- 404: Resource Not Found
- 401/403: Unauthorized/Forbidden Access
- Improved error messages with clear, actionable feedback.
- Standardized the error alert title to "Connection Error" for better clarity.
- Displayed errors in a monospace font to improve readability for command-line users.
- Logged full error details using console.error for better debugging.
- Introduced contextual suggestions (e.g., troubleshooting steps when clusteradm is missing).
- After Command Generation:
- Simplified the initial UI to focus on …

UI Enhancements, Error Handling Improvements & Design Consistency Updates

---

backend/go.mod
backend/k8s/resources.go
backend/routes/resources.go

feat: added support to create any k8s resources from local file

---

backend/namespace/namespace.go
package-lock.json

This PR optimizes WebSocket and API functions by improving resource fetching through namespace-based segregation. It ensures that sensitive resources are properly hidden while maintaining efficiency and security within Kubernetes environments.  
- Optimized WebSocket functions to fetch resources based on namespaces.  
- Updated API functions to retrieve resources through namespace filtering.  
- Ensured secrets and sensitive data are not exposed through API calls.  
- Conducted testing to validate improvements in performance and security.  
1. Deploy the updated WebSocket and API functions in a Kubernetes environment.  
2. Verify that resources are fetched correctly based on namespaces.  
3. Check that sensitive data is not exposed in API responses.  
4. Validate performance improvements …

Optimize WebSocket and API Functions for Secure Resource Fetching in Kubernetes

---

backend/routes/resources.go
backend/wds/common.go

This is not the ideal way to create what I am expecting, but it is also a good start to adding the functionality for this so we can start switching our WDS context.
Partial #328
https://github.com/user-attachments/assets/704bbdab-4542-4731-a9ff-f9209deb7f4f

feat: creating wds context using helm command and added websocket for better UX/Logs

---

backend/namespace/namespace.go

This PR enhances security and usability by filtering system namespaces (e.g., `kube-system`, `kube-public`) and sensitive resources (e.g., `secrets`, `configmaps`, `serviceaccounts`) from the namespace listings.  
This change ensures that critical Kubernetes resources remain secure and are not unintentionally exposed in API responses.  
Fixes #349

🔒 Filter System Namespaces & Sensitive Resources from Namespace Listings

---

src/components/login/KubeStellarLayout.tsx
src/components/login/LoginForm.tsx
src/components/login/NetworkGlobe.tsx
src/components/login/globe/Cluster.tsx
src/components/login/globe/CosmicDust.tsx
src/components/login/globe/DataPacket.tsx
src/components/login/globe/GlowingSphere.tsx
src/components/login/globe/LogoElement.tsx
src/components/login/index.tsx

- Changed the layout from 50/50 split to 70/30 split for left and right panels
- Updated responsive behavior to maintain full width on mobile devices
- Refactored error handling with a consolidated errors object
- Added proper form validation for username and password
- Improved error message display with animations
- Added custom styling for autofill to prevent browser defaults from breaking the UI
- Made password field required for better security
- Fixed password eye icon with transparent background
- Added overflow-hidden to the background container
- Replaced blur-3xl with more consistent blur-[100px]
- Added opacity-50 to decorative elements for consistent rendering
- Fixed inconsistent blending and sharp edges in background elements
- Fixed issues with the decorative blue blocks in …

Performance Optimizations - Render Loop Optimization - Layout Adjustment

---

backend/wds/bp/handlers.go
backend/wds/bp/utils.go
src/components/BindingPolicy/BPTable.tsx
src/components/BindingPolicy/CancelConfirmationDialog.tsx
src/components/BindingPolicy/ClusterPanel.tsx
src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/components/BindingPolicy/Dialogs/BPHeader.tsx
src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
src/components/BindingPolicy/PolicyCanvas.tsx
src/components/BindingPolicy/PolicyPanels.tsx
src/components/BindingPolicy/WorkloadPanel.tsx
src/components/BindingPolicy/constants/index.ts
src/components/BindingPolicy/styles/CreateBindingPolicyStyles.tsx
src/hooks/queries/useBPQueries.ts
src/pages/BP.tsx
src/types/bindingPolicy.ts

Implemented React Query to efficiently manage data fetching, caching, and synchronization across the application. Also, ensured that the binding policy UI maintains a consistent design and user experience for better usability and coherence.
Fixes #351 
- implemented react query 
- made dialogs UI  consistent for binding policy
- made table UI consistent for binding policy
-  Enhanced CreateBp to support YAML parsing and fix content-type handling.

Implemented react query and make the binding policy UI consistent

---

backend/its/manual/handlers/cluster.go
backend/routes/cluster.go

corrected available clusters api 

corrected available clusters api

---

src/components/ImportClusters.tsx

Fixes Unwanted Border Around Tabs

---

backend/k8s/resources.go
backend/routes/deployment.go
backend/routes/resources.go

* Add logs for all the resources inside one namespaces 
* You can also see the logs for the specific resources inside namespace 
```rs
// for the service inside namespace "my-namespace"
rahulxf@Rahuls-MacBook-Air-3 ~ % npx wscat -c http://localhost:4000/api/services/my-namespace/log
Connected (press CTRL+C to quit)
< [2025-03-22T19:13:55+05:30] ADDED: Kind=Service, Name=my-deployment, Namespace=my-namespace, UID=62093f11-8e43-452d-9260-a936efc57f0c
< [2025-03-22T19:14:35+05:30] ADDED: Kind=Service, Name=my-deployment2, Namespace=my-namespace, UID=6569cb90-1fdd-4037-9cc3-42afb401c0dc
< [2025-03-22T19:15:26+05:30] UPDATED: Kind=Service, Name=my-deployment2, Namespace=my-namespace, UID=6569cb90-1fdd-4037-9cc3-42afb401c0dc
< [2025-03-22T19:15:55+05:30] DELETED: Kind=Service, …
```

feat: real time logs using dynamicSharedInformerFactory and websocket

---

backend/namespace/namespace.go

`Optimize WebSocket for Instant Cluster Updates`  
This PR improves WebSocket performance to ensure real-time updates across the cluster with minimal latency. Key enhancements include:  
- Implementing WebSocket load balancing for efficient message distribution.  
- Reducing unnecessary reconnections to improve stability.  
- Enabling WebSocket compression to minimize payload size.  
- Optimizing message serialization/deserialization.  
1. Deploy the updated WebSocket implementation in the cluster.  
2. Broadcast a test message from one node.  
3. Verify that all nodes receive updates with reduced latency.  
- Real-time updates with a target latency of **<50ms**.  
- Improved WebSocket connection stability.  
Closes #392

Optimize WebSocket for Instant Cluster Updates

---

src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/hooks/queries/useBPQueries.ts

Integrating Drag and Drop binding policy backend api's with frontend.
Fixes #381 
- Integrated 2 backend routes ( quick-connect, generate-yaml).
- Created react queries functions to integrate the api's.

Integrating Drag and Drop binding policy backend

---

backend/k8s/resources.go
backend/routes/resources.go
public/examples/multiple-resource-example.yaml
public/examples/multiple-resource-with-ns.yaml

Fixes #409
https://github.com/user-attachments/assets/b52fcb3f-fc56-4b1b-8fec-1820ab71f3b4

support multiple resources configuration in one yaml file 

---

src/components/TreeViewComponent.tsx
src/context/WebSocketProvider.tsx

Fixed the lag which was coming after deploying the workload. Added the loader for the case when the data comes from backend but data is empty.
Fixes #413 
- Added a new hasValidData state in WebSocketProvider to track when valid data is received.
- We only set hasValidData to true when non-empty data is processed and valid.
- Updated the isLoadingTree condition in TreeViewComponentto use hasValidData for determining when to show the loader.

Fixed the lag after deploying the workload

---

backend/k8s/resources.go

fix: updated resourceKind logic in getResourceGVR

---

src/components/CreateOptions.tsx

Fixes #422
name and namespace will be same I changed in this commit [6263a64](https://github.com/kubestellar/ui/pull/421/commits/6263a64dfb442aa453a9eeffe64e916f0cc04273)

added generateRandomString resource name

---

backend/k8s/deployer.go
backend/k8s/resources.go
public/examples/multiple-resource-auto-ns-creation.yaml

If user tick the checkbox for auto creation namespace then it will create namespace for this and will not throw the error like "namespace does not exist"
Under the #52 

added logic for auto namespace creation if not exist

---

backend/k8s/deployer.go

**Title:** 🚀 Improve Helm Deployment by Managing Kubernetes Context & Enabling Concurrent Operations  
**Branch Name:** `enhance-helm-deployment`  
Fixes #430
This PR enhances the Helm deployment process by:  
1. **Managing Kubernetes Context Efficiently** – Ensures the correct Kubernetes context is set during deployment and restores the original context after execution.  
2. **Enabling Concurrent Operations** – Allows concurrent initialization and loading of Helm charts, reducing overall deployment time.  
- **Automatic Context Switching:** Saves the current Kubernetes context before deployment and restores it after execution to prevent accidental context modifications.  
- **Parallel Chart Initialization:** Uses multi-threading or asynchronous execution to speed up …

Enhance Helm deployment with context management and concurrency

---

src/components/Layout.tsx
src/components/menu/data.ts

Updated the Menu items order and Names
Fixes #455

Updated the Menu items order and Names

---

src/components/Layout.tsx
src/components/menu/data.ts

I have fixed the responsiveness issue. And made some changes in the icons
Continuation of #467

fixed responsiveness and added better icons

---

backend/routes/cookies.go
backend/routes/deployment.go
backend/routes/setup.go
backend/wds/common.go

Added two route set and get wds context 
// system-context : is current context on your system 
Get response : 
```js
`GET`
http://localhost:4000/wds/get/context
```
```js
`POST`
http://localhost:4000/wds/set/context
Body: 
{
"context": "wds2"
}
```
Partially Fix #473
Under the #52 

wip: added cookies functionality for setting up wds context

---

src/components/BindingPolicy/BPTable.tsx
src/pages/BP.tsx

Fixed the error that occurred after deleting a binding policy.
Fixes #479 
- Added a check to status call of binding policy.
- Status api should not be called just after the bp is deleted.

Fixed the error 400 on deleting a binding policy

---

backend/api/handlers.go
backend/routes/cluster.go

Patch api for label management in ITS
Fixes #450 

:pencil2:  Manage Labels in ITS Clusters

---

backend/main.go
backend/wecs/wecs.go

This pull request enhances the Kubernetes cluster monitoring capabilities by implementing comprehensive cluster metadata streaming. The new feature provides real-time, in-depth insights into cluster infrastructure, enabling more proactive and informed cluster management.
- Implemented detailed cluster metadata retrieval
- Extended WebSocket streaming to include cluster-level information
- Added intelligent caching mechanism for performance optimization
- **Node Information**
- Detailed node status tracking
- Resource capacity and allocation details
- Node health conditions
- Creation timestamps
- **Resource Quotas**
- Namespace-level quota tracking
- Hard limits and current resource usage visualization
- **Cluster Events**
- Comprehensive cluster-wide event logging
- Chronological event …

Implement Kubernetes Cluster Metadata Streaming  

---

backend/namespace/namespace.go

fix: added the CreationTimestamp in get ns

---

backend/routes/resources.go
backend/wds/list.go

```
// ListAllResourcesDetails api/wds/list - 
example - http://localhost:4000/api/wds/list
/ ListAllResourcesByNamespace api/wds/list/:namespace
example : http://localhost:4000/api/wds/list/default
```
Fixes #512
Under #52 

feat: list out all the k8s resources clusterScoped & ns Scoped

---

backend/k8s/resources.go
backend/main.go
backend/wds/common.go

Few of changes in this pr 
1) Updated the wds context creation, using kubestellar 0.27.2 as default and also added the `overwrite` field
2) Removed duplicate switch client set context function 
3) Added the statement to check if any cookies is mentioned so we will fetch the data from that context ( I mean we will not use the default wds1 then) - `Work in Progress`
Fixes #524
Under the #52 

fix: removed duplicate clientset, fixed the wds context creation

---

backend/installer/Prerequisites.go

This PR adds CPU architecture compatibility checks to the prerequisites checker to ensure KubeStellar is only installed on supported architectures.
- Added `ArchitectureStatus` struct to track architecture compatibility
- Implemented architecture verification checking against supported architectures (amd64/x86_64, arm64)
- Updated the prerequisites response to include architecture information
- Modified the display output to show architecture details
- Updated overall compatibility check to fail if architecture is incompatible
- Tested on amd64/x86_64 architecture to verify detection
- Simulated tests for unsupported architectures to verify behavior
- Confirmed clear feedback is provided when architecture is incompatible
Fixes #530

Add CPU architecture compatibility checks to prerequisites checker

---

backend/namespace/namespace.go

fix: namespaces quick

---

backend/wds/common.go
backend/wds/deployment/details.go
backend/wds/list.go

Improved the list view backend response time (Optimize it) Fixes #542
Integrate the redis for the list view Fixes #540
There is an issue with the switch context add logic to switch to those context which are present on the user system only 
Fixes  #541 
Under #52 

feat: list view optimization by ~80% , redis integration , fixes switch context logic

---

backend/namespace/namespace.go
backend/namespace/treeView.go

Eliminate the WebSocket handler and associated functions that are no longer needed, streamlining the codebase.
Fixes #548

Refactor: Remove unused WebSocket handler and related functions

---

backend/k8s/resources.go

updated the auto labelling logic in staged workload

---

backend/k8s/resources.go

fix: now the labels in ns and workload is same

---

backend/wds/bp/handlers.go
backend/wds/bp/utils.go

This PR fixes the issue in which a BP has workloads but the backend does not send it
Fixes #528
Fetching all the "Binding" resources. Then fetching the workloads from each and storing them in their respective bindingpolicy.workloads slice

workloads fixed

---

backend/main.go
src/components/ClustersTable.tsx
src/hooks/queries/useClusterQueries.ts

1. Added a new `useUpdateClusterLabels` mutation in the `useClusterQueries` hook to call the backend PATCH endpoint.
2. Created a `LabelEditDialog` component that allows users to add, edit, and delete labels.
- Added a "Manage Labels" dropdown button that appears when clusters are selected
- Implemented bulk label application to multiple selected clusters
- Modified the save function to handle both single and bulk operations
- Added Ctrl+F or / keyboard shortcuts to quickly focus the search field
- Added Escape key functionality to clear search and filters
- Included tooltips showing keyboard shortcuts to users
- Made labels clickable to filter the table by that specific label
- Added visual indicators when a label filter is active
- Implemented a clear filter button for easy removal of …

Feat: Edit labels to the ClustersTable component

---

src/components/ListViewComponent.tsx

This PR enhances the List View component by improving its responsiveness across different screen sizes and fixing pagination layout issues. The pagination controls were previously difficult to access on smaller screens, and list items didn't adapt well to mobile layouts.
Fixes UI responsiveness issues in list view mode
After: Pagination is now more prominent with proper spacing, and list items stack vertically on mobile with optimized spacing and content layout.
[Screencast from 16-04-25 02:32:49 PM IST.webm](https://github.com/user-attachments/assets/f8107cd0-412a-4300-9fac-c6d81c631c88)
These changes focus on improving the user experience specifically in list view mode. I've tested the implementation on multiple screen sizes to …

Fix: Improve list view responsiveness and pagination layout

---

src/components/DynamicDetailsPanel.tsx

Made multiple labels looks like tiles and its for different part of the project
Fixes #567

Staged workloads labels style improved

---

src/components/BindingPolicy/CanvasItems.tsx
src/components/BindingPolicy/ClusterPanel.tsx
src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/components/BindingPolicy/PolicyCanvas.tsx
src/components/BindingPolicy/PolicyDragDropContainer.tsx

Removed most of the hard coded things for the cluster logic with proper labels selection that can be easily dragged to the canavas
Fixes #568 
- Checked the cluster labels are working by properly by adding new cluster labels.
- Refactored the cluster labels selection for the binding canavas

Improved the cluster labels

---

backend/k8s/resources.go

Fixes #544
Under #52 
https://github.com/user-attachments/assets/4725824b-eef6-4b6c-b8d6-a56bbaea0ab7

improved the logs message and added more condition

---

src/components/ContextDropdown.tsx
src/components/TreeViewComponent.tsx
src/components/WecsDetailsPanel.tsx
src/components/WecsTopology.tsx

This PR updates the Stage workloads hierarchy and adds the necessary cluster configuration details in the Remote Cluster

Update Stage Workloads hierarchy and Add Cluster Details Frontend

---

src/components/BindingPolicy/ClusterPanel.tsx
src/components/BindingPolicy/PolicyCanvas.tsx
src/components/BindingPolicy/WorkloadPanel.tsx

Added check icon to mark the label item which is selected in the drag and drop binding policy.
Fixes #581 
- Added a check icon to both the cluster and workload label item which is selected for the binding canvas.

Added a check icon to show selected label item for the binding canvas

---

src/components/BindingPolicy/BPTable.tsx
src/components/BindingPolicy/Dialogs/BPHeader.tsx
src/hooks/queries/useBPQueries.ts
src/pages/BP.tsx

Fixes #588 
-  Improved the logic of delete selected to only delete the policy selected not all of them

Fixed the bulk deletion issue in bp

---

src/components/ListViewComponent.tsx
src/components/TreeViewComponent.tsx

This PR removes the labels from node elements in the stage workloads view and refactors the ListViewComponent for better performance.

This PR removes the labels from node in the stage workloads view and refactors the ListViewComponent.

---

backend/api/handlers.go

Label Fixes to add new labels correctly.

:christmas_tree:  Label Fixes for Adding New Labels 

---

backend/api/artifact.go
backend/k8s/deployer.go
backend/routes/artifacthub.go
backend/routes/setup.go

This PR adds support for deploying Helm charts directly from [Artifact Hub](https://artifacthub.io/), enhancing our application's capability to discover and deploy Kubernetes packages more easily.
Fixes #619
- Added new API endpoints for Artifact Hub integration
- Implemented search functionality for Artifact Hub packages
- Added deployment capability using Artifact Hub package identifiers
- Created repository listing functionality
- Added package details and default values retrieval
- Integrated with existing ConfigMap storage mechanism
- Added comprehensive error handling
- `POST /api/v1/artifact-hub/helm-deploy` - Deploy Helm charts from Artifact Hub
- `POST /api/v1/artifact-hub/packages/search` - Search for packages
- `GET /api/v1/artifact-hub/packages/:packageId/details` - Get …

 Add Artifact Hub Deployment Support

---

backend/routes/bp.go
backend/wds/bp/handlers.go
backend/wds/bp/utils.go
src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/hooks/queries/useBPQueries.ts

I have addressed the namespace issue in the wec that was causing the workloads to get deployed to the wec.
Fixes #616 
- Update the logic to handle the namespace after the bp is creatd for the wec.
- Now namespace in wec is smoothly getting created and workloads get deployed to the wec
- Verified by deploying various workloads using the helm

Namespace issue in the wec fixed after BP is created

---

src/components/BindingPolicy/BPTable.tsx
src/components/BindingPolicy/CanvasItems.tsx
src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
src/components/BindingPolicy/PolicyCanvas.tsx
src/components/BindingPolicy/PolicyDragDropContainer.tsx
src/components/BindingPolicy/WorkloadPanel.tsx
src/hooks/queries/useBPQueries.ts

Update to workload selection to make sure every workload label is getting selected in the workload panel. Also updated the bp status to get updated when changes to active from inactive.
Fixes #618 

Fixed the issue with workload selection in click and drop BP

---

backend/wds/common.go

Improved #328
Under the work #52 
```
// for test
npx wscat -c "ws://localhost:4000/api/wds/context?context=wds2&version=0.27.2"  
```

fix: improved the logic & error message for CreateWDSContextUsingCommand

---

src/pages/BP.tsx

Commented out  as suggested for the release. 

Commented out the Bp visulaise view for the Biding Policy

---

src/components/ContextDropdown.tsx
src/components/ListViewComponent.tsx
src/components/TreeViewComponent.tsx

This pull request adds a feature to filter workloads by context using a dropdown menu. Each context shows a count of relevant workloads. This improves the user experience by enabling targeted views across contexts like wds1, wds2, and wds3.

 Added Context-Based Filtering Dropdown

---

src/components/BindingPolicy/WorkloadPanel.tsx

fix: dropped the cluster-scoped label and Cluster text 

---

src/components/ListViewComponent.tsx

list view show 25 obj per index

---

src/components/BindingPolicy/CreateBindingPolicyDialog.tsx

Updated the naming convention for the binding policies created from the  click and drop
Fixes #640 

Updated the bp naming for click and drop

---

src/components/BindingPolicy/WorkloadPanel.tsx
src/hooks/queries/useBPQueries.ts

Updated the workload panel in the click and drop binding policy to show all the resources available. Also remove some default namespaces.
Fixes #422 

Updated the workload panel to show all the resources

---

src/components/TreeViewComponent.tsx

…d enhance no workloads found display
Fixes #645 

 [Enhancement] Added ReactFlow background to empty state of Staged Workloads

---

backend/k8s/deployer.go

**Pull Request Description**
**Summary**
This PR introduces a Helm **post-renderer** (`labelInjector`) that automatically injects a `kubestellar.io/workload: <label>` annotation into the `metadata.labels` of **every** Kubernetes manifest produced by Helm charts. By decoupling label injection from individual chart templates, this enhancement guarantees consistent workload labeling across all resource kinds—Deployments, Services, ConfigMaps, Secrets, CRDs, and more—without requiring chart authors to add boilerplate.
---
**Changes**
* **New** `labelInjector` type implementing `postrender.Run`, which:
* Splits the aggregated YAML output into individual documents.
* Parses each into a `map[string]interface{}`, ensures `metadata.labels` exists, and adds the workload label.
* Re-serializes and …

Add labelInjector post-renderer for Kubernetes manifests

---

src/components/Workloads/WorkloadLabelInput.tsx

Prefix text in workload lable input box visible in light mode
Fixes #652 

Prefix text in workload lable input box visible in light mode

---

src/components/CreateOptions.tsx
src/components/Workloads/AirtfactTab/ArtifactHubTab.tsx
src/components/Workloads/AirtfactTab/DirectDeployForm.tsx
src/components/Workloads/AirtfactTab/RepositoriesListForm.tsx
src/components/Workloads/AirtfactTab/SearchPackagesForm.tsx

This PR introduces a new ArtifactHub tab in the "Create Workloads" UI. It enhances the workload creation process by enabling users to browse and deploy packages from ArtifactHub directly.

Feature artifact tab in the create workload option

---

src/components/ContextDropdown.tsx

This PR introduces the functionality to create new contexts within the platform. Users can now dynamically add custom contexts from the UI, which will be reflected across the context dropdown and used for workload filtering.

 Added Feature to Create/Add New Contexts

---

src/components/CreateOptions.tsx

Fixed jumpiness in modal in Staged Workloads tab when switching between tabs
Fixes #662 
https://github.com/user-attachments/assets/0c2dae07-1700-43fb-b73d-9d0140b9c749

Fixed jumpiness in modal in Staged Workloads tab when switching between tabs

---

src/components/BindingPolicy/ClusterPanel.tsx
src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/components/BindingPolicy/PolicyDragDropContainer.tsx
src/components/BindingPolicy/WorkloadPanel.tsx
src/hooks/queries/useBPQueries.ts

Adding missing resources like PVC, statefulsets, configmaps, secrets which were not getting properly to the wec after the BP was created causing error in running the pods
Fixes #670 

Added some missing resources

---

src/components/StyledComponents.tsx
src/components/Workloads/AirtfactTab/ArtifactHubTab.tsx
src/components/Workloads/AirtfactTab/DirectDeployForm.tsx
src/components/Workloads/AirtfactTab/RepositoriesListForm.tsx
src/components/Workloads/AirtfactTab/SearchPackagesForm.tsx
src/components/Workloads/GitHubTab.tsx
src/components/Workloads/GitHubTab/GitHubTab.tsx
src/components/Workloads/HelmTab/CreateOwnHelmForm.tsx
src/components/Workloads/HelmTab/HelmTab.tsx
src/components/Workloads/HelmTab/PopularHelmChartsForm.tsx
src/components/Workloads/HelmTab/UserCreatedChartsForm.tsx
src/components/Workloads/UploadFileTab.tsx
src/components/Workloads/WorkloadLabelInput.tsx
src/components/Workloads/YamlTab.tsx

This pull request resolves inconsistencies in the WorkloadInput text field behavior across all tabs. It ensures a uniform input experience by maintaining consistent styles, validation, and state synchronization across different sections of the application.

Fixed WorkloadInput Text Field Across All Tabs

---

src/components/Header.tsx

This adds the username of logged in user

Added username beside profile

---

src/components/WecsTopology.tsx

…uster view
This PR addresses a UI issue in the remote cluster view where pods or child objects were not vertically aligned properly. The fix ensures consistent alignment and improves visual clarity across different screen sizes and contexts.

Fix Vertical Alignment of Pods/Child Objects in Remote Cluster View

---

src/components/BindingPolicy/ClusterPanel.tsx
src/components/BindingPolicy/WorkloadPanel.tsx

Added the feature to edit the workload labels directly from the click and drop UI of BP
Fixes #592 
- Added a labels button next to create wokload option.
- Now we can edit the labels in 2 ways one directly adding a label to the resource and other one is by clicking the labels button on top 
- Next is to add bulk labeling to both workloads and clusters.

Added the feature to edit the workload labels 

---

src/components/ClustersTable.tsx

Fixes #696 
- [] I have written unit tests for the changes (if applicable).
- [] I have updated the documentation (if applicable).
✅Replace pencil (✏️) icon with label/tag icon (🏷️ or suitable UI library icon).
✅Ensure hover text shows "Edit Label" or similar, clear action.
✅Remove tick mark (✓) from the status indicator.
✅Replace with a cleaner badge (e.g., 🟢 Active or use a green dot with Active text).
✅Use Tailwind or badge components for consistent look.
- ✅Detect when multiple clusters are selected.
- ✅Hide individual label edit icons (pencil or label icon) in multi-select mode.
- ✅Show only the "Add Labels" dropdown or bulk label action.
- ✅Disable bulk label action when no cluster is selected.
Optional (Nice to Have)
- ✅Add …

Added label tag , and handle multi cluster selection

---

src/components/BindingPolicy/WorkloadPanel.tsx

Added a placeholder text in workload serach in click and drop UI. The placeholder text is  "kubestellar.io/workload".

Added a placeholder text in workload serach

---

src/components/DynamicDetailsPanel.tsx
src/components/TreeViewComponent.tsx

- adding nodeType to context menu state
- conditionally rendering the Delete option based on nodeType.
Fixes #690 
https://github.com/user-attachments/assets/b6f65391-be7d-4037-b28c-ed9f98b11cb3

fix menu items button response for wds1

---

src/api/auth/constant.ts
src/api/auth/index.ts
src/api/auth/types.ts
src/components/Header.tsx
src/components/ProtectedRoute.tsx
src/components/PublicRoute.tsx
src/components/login/LoginForm.tsx
src/hooks/queries/useLogin.ts
src/hooks/useAuth.ts

Implemented useLogin and useAuth hooks

---

src/components/DynamicDetailsPanel.tsx

This PR addresses the issue of incorrect namespace information being displayed in the context details panel. 

Fix: Incorrect Namespace Info in Context Details Panel

---

backend/wecs/wecs.go

`feature/comprehensive-k8s-resources`
Implement comprehensive Kubernetes resource WebSocket streaming
This PR enhances our existing WebSocket-based Kubernetes resource streaming to include all API resources available in the cluster. Currently, we only stream a limited subset of resources, but this implementation provides complete monitoring and visualization by streaming all available resources that the Kubernetes API provides.
- Modified `StreamK8sDataChronologically` function to handle all Kubernetes resources
- Added support for both namespaced and cluster-wide resources 
- Implemented handlers for all resources listed in `kubectl api-resources` output
- Added a new `getClusterWideResources` function to handle non-namespaced resources
- Maintained compatibility with existing Redis …

Enhance StreamK8sDataChronologically to process additional Kubernetes resources

---

src/components/WecsDetailsPanel.tsx
src/components/WecsTopology.tsx

This PR introduces the ability to select and execute into a specific container within a pod that runs multiple containers. It improves user control during debugging and management scenarios.

Added multi-container select option in the Exec Pod

---

backend/wecs/wecs.go

This PR enhances our Kubernetes resource handler to provide complete coverage of all Kubernetes resource types and display them in chronological order. It significantly improves the user experience by offering a comprehensive view of cluster resources and their relationships.
- **Added support for all Kubernetes resource types** across all API groups
- **Implemented chronological sorting** of resources based on creation timestamps
- **Preserved hierarchical relationships** between related resources (e.g., Deployments → ReplicaSets → Pods)
- **Optimized Redis caching** with multi-level caching strategy
- **Improved WebSocket handling** for more reliable streaming
- Core resources: ServiceAccounts, Endpoints, ResourceQuotas, etc.
- Apps resources: ControllerRevisions
- Networking resources: …

Refactor StreamK8sDataChronologically to enhance resource processing and sorting logic

---

Dockerfile
docker-compose.yml
src/components/KubeStellarStatusChecker.tsx
src/pages/InstallationPage.tsx
src/routes/routes-config.tsx

This PR introduces a **comprehensive and user-friendly installation flow** for **KubeStellar**, aimed at enhancing the onboarding experience.  
It includes automatic status checking, environment validation, and a multi-step guided setup.
---
- Acts as a **router guard** to check the KubeStellar installation status  
- Redirects users based on their installation state  
- Prevents access to protected routes if KubeStellar is not installed  
- A **multi-step guided UI** for installing KubeStellar  
- **Prerequisites checker** with real-time feedback  
- **Platform selection** (e.g., `kind`, `k3d`) for flexibility  
- **Copy-to-clipboard** command blocks for easy execution  
- **Docker-friendly**: skips checks if `VITE_SKIP_PREREQUISITES_CHECK` is set  
- New route added: `/install`  
- …

KubeStellar Installation Flow Enhancement

---

src/components/ContextDropdown.tsx
src/components/DynamicDetailsPanel.tsx
src/hooks/queries/useWebSocketQuery.ts
src/hooks/useWebSocket.ts

Implemented useWebSocketQuery to use it for useWebsocket hook.

---

src/components/ListViewComponent.tsx

Fixed Duplicated namespace in List View Staged Workloads

---

src/pages/InstallationPage.tsx
src/routes/routes-config.tsx

Fix-bug KS Installation Status Detection

Fix KS Installation Status Detection

---

src/components/Workloads/AirtfactTab/ArtifactHubTab.tsx

This PR aims to make the Apply and Cancel buttons consistent in the Artifact Hub interface, following the design patterns seen in Helm and GitHub.

Add Consistency to Apply and Cancel Buttons in Artifact Hub (Similar to Helm and GitHub)

---

backend/k8s/resources.go

changed the labelKey to kubestellar.io/workload (backend)

---

src/components/ContextDropdown.tsx

If there are multiple contexts, now it will appear in sorted order instead of random order
Fixes #746 

Context list sorted

---

backend/k8s/deployer.go

This PR enhances the workload labeling functionality to ensure consistency by applying the `kubestellar.io/workload` label to namespaces as well as the resources they contain.
- Modified `EnsureNamespaceExists` to accept a `workloadLabel` parameter
- Added logic to apply the workload label when creating new namespaces
- Added logic to update existing namespaces with the workload label
- Updated all callers of `EnsureNamespaceExists` to pass appropriate labels
- Internal storage operations pass empty string as they don't need workload labeling
Previously, when deploying with a workload label, only the resources themselves would get labeled, but their containing namespaces would not. This created inconsistency in workload identification and made filtering more difficult. Now, workload …

Add workload label support to namespace creation in DeployManifests

---

src/api/auth/index.ts
src/hooks/queries/useLogin.ts
src/lib/api.ts

FIX: Login error and issues

---

backend/wecs/wecs.go

Adds support for seeing previous logs of a pod

--previous supported for viewing logs

---

src/components/ImportClusters.tsx
src/components/KubeStellarStatusChecker.tsx
src/lib/api.ts
src/pages/InstallationPage.tsx
src/routes/routes-config.tsx

The flow appears to be working correctly and aligns with the intended user experience:
---
- When a user first opens the application:
- If KubeStellar is not installed, they are redirected to the installation page.
- If KubeStellar is already installed, they are taken directly to the login page.
---
- Users can:
- Check prerequisites
- Choose a platform 
- View installation instructions
- The application performs periodic status checks to detect if the installation has completed.
---
- Once KubeStellar is successfully installed:
- The UI automatically updates
- Users can then navigate to the login page.
---
This PR ensures a smooth and automated flow from installation to login, improving the experience for both new and returning users.

Fix: KubeStellar Installation Status detection

---

src/components/Workloads/UploadFileTab.tsx
src/components/Workloads/YamlTab.tsx

Made the autNs state to true by default. 
refer to [772 ](https://github.com/kubestellar/ui/issues/772#issuecomment-2881348718)comments

Create Namespace true by default

---

src/components/DynamicDetailsPanel.tsx
src/components/WecsDetailsPanel.tsx

Fixes #756 
improved the YAML and JSOn buttons styling and layout
Uploading Screen Recording 2025-05-15 at 1.09.52 AM.mov…

fixed button yaml and json

---

backend/wds/bp/handlers.go
backend/wds/bp/utils.go

This PR replaces all fmt.Printf debug and info print statements in the Binding Policy backend handlers with structured logging using zap. The goal is to establish consistent, structured, and production-ready logging across our internal backend operations.
Fixes #283 

refactor: replace fmt.Printf with zap logging in BindingPolicy handlers

---

src/components/ui/BPSkeleton.tsx
src/pages/BP.tsx

This PR implements skeleton loading for /src/pages/BP.tsx using the `BPSkeleton` component.

Skeleton loading for /src/pages/BP.tsx

---

package.json
src/components/ClustersTable.tsx

Fix: add the edit pencil icon (for edit labels) into the its manual section

---

package-lock.json
package.json
src/hooks/queries/useBPQueries.ts

bug: Removed all the ascii and also collapse the managed fields

---

package.json
src/components/ClustersTable.tsx

Fix: Add dark themed status filter in dark theme

---

CONTRIBUTING.md
README.md

Fixes #796
---
This pull request adds important setup information to enhance the documentation for new contributors and users of KubestellarUI:
1. Added Docker Desktop host networking note: Added a crucial note in the README.md that instructs users of Docker Desktop to enable host networking in Settings > Resources > Network. This helps prevent connectivity issues between containers and the host machine, which is particularly important for Redis and API service communication.
2. Reorganized documentation structure: Moved development tooling sections (GolangCI-Lint installation and linting commands) from README.md to CONTRIBUTING.md, making the README cleaner and more focused on initial setup while keeping developer-specific workflow information in the contribution guide.
---
These changes …

[DOCS] Update Readme and Conributing .md

---

src/components/providers/ToastProvider.tsx
src/main.tsx

Fixes #807 
Enhanced the toast notification system with improved visual design, animations, accessibility, and user experience. The changes create a more polished, professional, and user-friendly notification system that provides better feedback and interaction.
- **Modern Styling**
- Increased border radius (16px) for a contemporary look
- Enhanced box shadows for better depth perception
- Semi-transparent backgrounds with blur effect (backdrop-filter)
- Improved typography with better line height and letter spacing
- Consistent padding and spacing
- **Entry Animation**
- Smooth slide-in with scale effect
- Custom cubic-bezier timing for natural movement
- Opacity transition for smooth appearance
- **Type-Specific Animations**
- Success: Gentle pulse effect with green glow
- Error: Shake …

UI Enhancement: Differentiate Toast Message Colors Based on Type & UI/UX Improvement

---

src/components/DynamicDetailsPanel.tsx
src/components/TreeViewComponent.tsx
src/components/Wds_Topology/FlowCanvas.tsx
src/components/Wds_Topology/NodeLabel.tsx
src/components/WecsTopology.tsx

This PR Introduces the Filters out objects specifically for log tab and increase the gap between the nodes.

filter object for log tab, and increase node spacing

---

src/components/providers/ToastProvider.tsx

**These changes create a more cohesive and professional look while maintaining excellent accessibility and user experience. These refinements create a more premium, polished feel while maintaining excellent performance and accessibility.**
Related PR #812

Improved color combinations & 3D Effects in Toast

---

src/components/BindingPolicy/PolicyDragDropContainer.tsx
src/components/BindingPolicy/WorkloadPanel.tsx
src/components/CreateOptions.tsx
src/components/TreeViewComponent.tsx
src/components/WecsTopology.tsx
src/context/WebSocketProvider.tsx
src/context/webSocketExports.ts
src/hooks/queries/useWebSocketQuery.ts

Fixes https://github.com/kubestellar/ui/issues/800
Description
This PR fixes all 9 existing ESLint warnings in the codebase to ensure clean and consistent code. The changes include wrapping functions in useCallback and useMemo to fix hook dependency issues, removing an unused eslint-disable directive, separating shared constants to avoid fast-refresh warnings, and adding a missing dependency in a useEffect hook. After these fixes, running npm run lint (or yarn lint) now shows zero warnings. These improvements help maintain code quality and prevent potential runtime issues.

[FIX] All Lint Warnings (Currently 9)

---

src/components/BindingPolicy/ClusterPanel.tsx
src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/components/BindingPolicy/PolicyDragDropContainer.tsx
src/components/ClustersTable.tsx
src/hooks/queries/useBPQueries.ts
src/hooks/queries/useClusterQueries.ts
src/pages/BP.tsx
src/pages/ITS.tsx
src/types/bindingPolicy.ts

Updated the cluster labels api in click and drop, cluster table.
Fixes #832 
- used the new api  - /api/new/clusters to get the cluster labels in click and drop
- Fixed in minor bug in creating bp

Integrated the new its api into bidning policy cluster labels.

---

backend/Dockerfile
backend/wds/common.go

* Updated the `Dockerfile` to install `kubflex` ([here](https://github.com/kubestellar/kubeflex?tab=readme-ov-file#installation)
* updated the logic for checking the system is using k3d-kubeflex or kind-kubeflex (I am giving priority to k3d) 
* using kubestellar 0.27.2 as default (recommended)
Under #52

fix: added condition for check both kind & k3d kubeflex  

---

package.json

This PR adds a new lint:fix script to the package.json file to automate fixing linting issues. This script leverages ESLint's --fix flag to automatically correct fixable linting errors.
---
- Added "lint:fix": "eslint . --fix" to the scripts section in package.json
- Developers can now easily fix automatically correctable linting issues with a single command
- Improves code quality by making it simpler to maintain consistent code style
- Saves development time by automating routine formatting fixes

[FEAT] Added the script for fixing lints

---

src/components/WecsTopology.tsx

fix: Enhance Pod Context Menu with Exec Pod Option

---

package-lock.json
package.json

This PR updates the js-yaml package from version 3.13.1 to 4.1.0 in the devDependencies. The previous version has a known security vulnerability that allows arbitrary code injection, which poses a significant risk.
By upgrading to 4.1.0, this patch addresses the vulnerability and improves the overall security posture of the project.
Ref: https://security.snyk.io/vuln/SNYK-JS-JSYAML-174129

fix: mitigate code injection risk by bumping js-yaml to 4.1.0

---

src/pages/BP.tsx

Updated the ITS api in BP

---

src/components/ClustersTable.tsx

Updated cluster context in clusters table

---

src/components/Clusters.tsx
src/components/CommandPalette.tsx
src/components/Header.tsx
src/components/Layout.tsx
src/components/ProfileSection.tsx
src/components/menu/Menu.tsx
src/components/menu/MenuItem.tsx
src/components/ui/ClusterSkeleton.tsx
src/components/ui/HeaderSkeleton.tsx
src/hooks/queries/useClusterQueries.ts
src/index.css
src/lib/theme-utils.ts
tailwind.config.js

- Completely **modernized, interactive dashboard** with a strong focus on **best-in-class UX**
- **Flexible, responsive header** with improved layout and usability
- Added **Command Palette** for quick actions and navigation
- **Collapsible sidebar menu** for a cleaner, focused experience
- Real-time **Cluster count**, **status**, and **health overview**
- Integrated BP information display
- 🔥 **Recent Activity section** – major UX win for tracking updates and events
- Removed outdated and unused `k3d-kubeflex` dropdown to streamline the UI
This revamp transforms the dashboard into a **truly user-friendly** and **visually engaging interface**. It's faster, cleaner, and smarter — empowering users to navigate and monitor clusters effortlessly.
---
💬 Feedback and suggestions are welcome!

Feat: Unbeatable Dashboard Revamp: Next-Level UX, Cluster Health, & Recent Activity

---

src/components/BindingPolicy/WorkloadPanel.tsx
src/components/OnboardingLogsDisplay.tsx
src/hooks/queries/useBPQueries.ts

Updated the workload panel to show all the resources under the particular labels correctly. Removed the dollar sign from the import cluster.
Fixes #881 
- Removed the dollar sign from import cluster
- Updated the workload panel to show all the resources.

Fixed the resources and labels issues in BP

---

src/components/Clusters.tsx
src/components/providers/ToastProvider.tsx
src/pages/InstallationPage.tsx

Feat: UI/UX Enhancements and Toast Improvements
- Updated the installation page toast message from:  
`"KubeStellar is not installed. Installation progress will be checked automatically."`  
**to**  
`"Kubeflex cluster not found. Follow steps to set up KubeStellar environment."`
- Made the message more concise and action-oriented, focusing on the Kubeflex cluster issue and providing clear next steps.
- Darkened toast background colors for better contrast and reduced eye strain.
- Made toasts more compact by reducing padding, font size, and line height.
- Removed top shimmer animation; kept loading animation only at the bottom.
- Added a smooth sliding animation for the loading state.
- Enhanced visual aesthetics with darker gradients and more subtle borders.
- Optimized animation …

Feat: UI/UX Enhancements and Toast Improvements

---

src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
src/components/BindingPolicy/PolicyDragDropContainer.tsx
src/components/BindingPolicy/PolicyNameDialog.tsx

Added a dialog box to update the binding policy name while creating the bp using the click and drop.
Fixes #882 
- Added a new component for the update of binding policy name 
- Integrated this component with existing flow.
- Updated the function of random bp name generator

Added the option to add the BP name

---

backend/redis/redis.go
backend/wds/bp/handlers.go
backend/wds/bp/utils.go

This PR implements Redis-based caching for BindingPolicy operations.
Manually tested storing, retrieving, and deleting binding policies in redis CLI.
Fixes #282 

add redis cache for binding policy storage

---

backend/wds/common.go
src/components/Wds_Topology/FlowCanvas.tsx

Free scrolling on the FlowCanvas

---

backend/api/handlers.go
backend/wds/bp/handlers.go
src/components/ClustersTable.tsx
src/hooks/queries/useClusterQueries.ts

fixed the delete labels and edit labels and protected the default labels.
https://github.com/user-attachments/assets/36f0cb26-5ffd-4c3b-a668-0f819f18cecb

Delete and Edit labels in cluster

---

src/components/Workloads/CancelConfirmationDialog.tsx
src/components/Workloads/GitHubTab/CreateFromGitHubForm.tsx

This PR fixes two minor issues in the UI codebase:
1. incorrect border width.
2. correct grammer in text.

Fix/minor UI issues

---

backend/redis/redis.go
backend/wds/bp/handlers.go
backend/wds/bp/utils.go

Fixed all the edge cases for the redis for the binding policy.
Fixes #909 
- Added cache miss detection
- Updated the redis availability check
- Added Watch Event Synchronization

Updated th redis for Binding Policy

---

backend/api/deploy.go
backend/routes/gitops.go

<html><head></head><body><h1>🚀 Enhanced API Functionality and Performance Improvements</h1>
<h2>📋 Pull Request Summary</h2>
<p>This PR significantly enhances the KubeStellar deployment API with improved error handling, performance optimizations, better security, and comprehensive new endpoints for deployment management.</p>
<p><strong>Related Issues:</strong> #931 (API Functionality Improvements)</p>
<h2>🎯 <strong>Key Improvements</strong></h2>
<h3>📈 <strong>Performance Enhancements</strong></h3>
<ul>
<li><strong>40-60% faster repository operations</strong> through concurrent file fetching</li>
<li><strong>Shallow git clones</strong> with <code>--depth 1</code> for faster repository cloning</li>
<li><strong>Semaphore-based rate limiting</strong> (max 5 concurrent GitHub API requests)</li> …

🚀 Enhanced API Functionality and Performance Improvements

---

backend/routes/metrics.go
backend/routes/setup.go

This PR introduces a complete metrics and monitoring system for the KubeStellar deployment API, providing real-time insights into system health, deployment statistics, component status, and performance metrics.
Fixes #932
- **Component Health Tracking** - Individual status for Redis, Kubernetes, GitHub API
- **Overall System Health** - Aggregated health status with percentage calculation
- **Live Connectivity Tests** - Real-time checks for all external dependencies
- **Degradation Detection** - Early warning system for component issues
- **GitHub Deployment Statistics** - Total, webhook, manual, and failed deployments
- **Helm Deployment Statistics** - Active, failed, and succeeded deployments  
- **Deployment Trends** - Historical data and recent activity tracking
- **Success Rate …

Comprehensive Metrics and Monitoring System

---

src/components/WecsDetailsPanel.tsx
src/components/WecsTopology.tsx
src/context/WebSocketProvider.tsx
src/hooks/queries/useLogin.ts
src/pages/BP.tsx

Fixed all lint warnings

---

Dockerfile
README.md
backend/Dockerfile
docker-compose.yml
nginx.conf

This PR adds comprehensive environment variable support to the Docker Compose setup and migrates container images from Docker Hub to GitHub Container Registry (GHCR), making the application more flexible, secure, and configurable for different environments (development, staging, production).
- ✅ Added environment variable substitution with fallback defaults using `${VAR:-default}` syntax
- ✅ All hardcoded values are now configurable via environment variables
- ✅ Maintains backward compatibility with existing setups
- ✅ Migrated from Docker Hub to GitHub Container Registry (GHCR)
- ✅ Updated base images to use `ghcr.io/kubestellar/` namespace
- ✅ Improved image security and reliability with GHCR hosting
- ✅ Created dynamic nginx configuration using environment variables
- ✅ `NGINX_HOST` …

Add Environment Variable Support and Migrate to GHCR

---

backend/wds/bp/handlers.go

Remove redundant nil checks 

---

.github/workflows/greeting.yml

Updating Greetings CI  Version and Permission

---

.husky/pre-commit

Implement gofmt formatter in precommit

---

docs/design-progress.md

This pull request introduces a new markdown file, `design-progress.md`, placed in the `docs/` folder. It documents the progress of the CNCF LFX Mentorship Design Program for KubeStellar.
The file serves as a **single source of truth** for all design-related activities during the mentorship, ensuring transparency, traceability, and alignment with project goals.
- 📆 **Detailed Timeline**: Phase-wise breakdown from UI audit to final design handoff.
- 🔗 **Key Resources**:
- [FigJam Board – UI Audit](https://www.figma.com/board/IHLBwlFC6i4Ibh2DVIzBxX/KubeStellar%E2%80%AFv0.27.2-Documentation--UI--and-Design-System-Audit?node-id=0-1&t=SK5oQyifTdi2ji7C-1)
- [Google Doc – Goals & Scope](https://docs.google.com/document/d/1m0dAD3S4ShM32hw5k2wqGv-CZeFhnKI3t-Eto1MfVis/edit?usp=sharing)
This document …

Add design-progress.md to track UI/UX deliverables and PRs

---

backend/wds/common.go

This PR enhances ListContexts() by introducing structural validation and improved error handling. It verifies that each "wds" context includes a non-empty Cluster field and added logging
Fixes #865 

Improved logging to ListContexts() for WDS context filtering

---

backend/api/plugins.go
backend/plugin/plugins/manager.go
backend/routes/gitops.go
backend/routes/plugins.go

Resolves #1027 
Created a mock Apis for now as because of this frontend implementation of marketplace was blocked.
this will enhanced in future

Added Mock APIs and their Routes

---

src/components/BindingPolicy/BPPagination.tsx
src/locales/strings.en.json

Improve Binding Policy Count in Pagination

---

backend/k8s/client.go
backend/middleware/auth.go
backend/redis/redis.go
backend/services/clusterService.go
backend/wecs/exec.go

Add logs to backend services like redis, middlreware , etc for better user developer experience
Fixes #991 
1. for now only addedd logs for `redis.go`  and have to do for other files, if this is good I will follow for other files for now , leave it for review and 
2.on running project on local development it is working but docker compose is not working for frontend  because I have `amd64` and project using `arm` I think it should be updated .
3. on hitting `localhost:4000/login` and putting password `admin` and username: `admin` it shows `invalid crendentials` even my redis container is runing . I read `readme.md`  and `contributer.md` two three times but same problem.

chore: add logs in `backend Services`

---

backend/api/cluster_logs.go

Add logging to the cluster_logs.go service 
Fixes #1074 

✨  Improve cluster_logs.go service by adding logging

---

.github/workflows/preview-cleanup.yml
.github/workflows/preview.yml

using a cluster to host a preview of the UI for the purpose of testing/evaluating PR contents
Fixes #1028 

using GHA to setup preview of KS ui

---

.github/workflows/preview.yml

trying to fix EOF stuff

---

.github/workflows/preview.yml

add manual launch

---

.github/workflows/preview.yml

fix kubeconfig

---

src/components/ClusterDetailDialog.tsx

Add proper naming of the cluster details

---

src/locales/strings.en.json
src/locales/strings.ja.json

This PR adds Japanese localization support to the user interface. I verified all pages as much as possible.
By the way, I found a minor typo at https://github.com/kubestellar/ui/blob/dev/src/locales/strings.en.json#L8
The fix is also included in this PR.
https://github.com/kubestellar/ui/issues/963

Add Japanese localization

---

.github/workflows/preview.yml

make ghcr login static user

---

.github/workflows/preview.yml

update with secret for pulls

---

src/components/QuickConnectTab.tsx

Fixed missing dependecy array and lint errors in quick connect for clusters.
Fixes #1121 
- Add use-effect array and fixed the corresponding lint errors

Fixed missing dependecy array and lint errors

---

docs/design-progress.md

This PR adds a detailed progress update under the **Structure & Strategy – Information Architecture & Flow Planning** section. It covers:
- ✅ Review of current Information Architecture (IA)
- 📁 Observations and proposed hierarchy improvements
- 🧭 Navigation design audit:
- Header
- Sidebar
- Footer
- Breadcrumbs
- 🔄 Key user flows mapped:
- Manual Setup Flow
- OCM-Based Setup Flow
- Workload Execution Flow
- Teardown Flow
- 🚧 Identified content & functional gaps across documentation
These updates establish a clear baseline for restructuring the docs and improving usability across the site.

docs: Add progress update on IA Structure & Key User Flowsprogress update

---

.github/workflows/preview.yml

image reg for backend

---

src/locales/strings.es.json

Add Español language to the Plugin UI
Fixes #1158 
https://github.com/user-attachments/assets/da5fccc3-0ff6-44ba-bf8f-2e0b74fddebc

feat: add Español language to the Plugin UI

---

src/locales/strings.ja.json

This PR adds japanese language support for plugin.
Fixes #1157

feat(ln): Add japanese language support for plugin

---

chart/values.yaml

Updated ....version updated for kubectl_version

---

src/pages/InstallationPage.tsx

Fixes #1175 
https://github.com/user-attachments/assets/5f6d0ac3-5e7c-4822-a977-e1c9a2fa1ca8

Implemented Dark-Light Theme on the Installation Page

---

backend/Makefile

Updated Makefile for better UX

---

README.md
backend/.env.example
backend/admin/auth.go
backend/docker-compose.yml
backend/health/health.go
backend/main.go
backend/middleware/auth.go
backend/models/user.go
backend/postgresql/Database/connection.go
backend/postgresql/config.go
backend/routes/health.go
backend/routes/jwt.go
backend/utils/jwt.go
docker-compose.yml

Add PostgreSQL connection logic, refactor configuration loading, and enhance JWT authentication. Introduce comprehensive health check endpoints and update Docker configuration for PostgreSQL and Redis services. Update documentation to reflect new setup instructions.
Fixes #1181

Implement PostgreSQL connection and health check endpoints

---

hack/lima-kubestellar.yaml

This PR introduces a Lima template (lima-kubestellar.yaml) that sets up both KubeStellar (KS) and KubeStellar UI in a single environment using one command. This helps contributors and demo users quickly spin up a complete, local setup.
closes #967

✨feat: add Lima environment setup for KS UI and KS testing 

---

backend/.env.example

Removed extra JWT_SECRET from backend/.env.example

---

.prettierignore
CONTRIBUTING.md
README.md
prettier.config.js

This PR significantly improves the CONTRIBUTING.md file by adding missing PostgreSQL integration setup instructions .
Fixes #1193

Improve CONTRIBUTING.md: Added PostgreSQL Integration Guide

---

.github/workflows/preview.yml
docs/how-to-install-and-use-kubestellar-ui.md
docs/ui/README.md

Description:
This PR addresses [Issue #968](https://github.com/kubestellar/ui/issues/968) by adding documentation for the KubeStellar UI, making it easier for users and contributors to get started.
What’s Included:
•	docs/ui/README.md: Overview of the Kubestellar UI, features, usage guide, and contributing section.
•	docs/ui/INSTALL.md: Step-by-step installation and setup instructions.
•	Placeholder for UI screenshots under docs/ui/images/ (to be added later).
Highlights:
•	Covers prerequisites, setup, and UI walkthrough.
•	Written in Markdown and ready to be integrated into the official docs site.
•	Can be linked into the main kubestellar.io navigation structure.
Fixes:
Closes #968

✨ Add Kubestellar UI Documentation and Installation Guide

---

.github/workflows/preview.yml
backend/wds/bp/utils.go

Description:
This pull request implements a watcher for BindingPolicy resources, ensuring that any changes (ADDED, MODIFIED, DELETED) are reflected in Redis in near real-time. This keeps the UI in sync with the latest state of the backend without requiring manual refreshes or polling.
Key Highlights:
•	Introduced watchOnBps() to listen for Kubernetes events related to BindingPolicy.
•	Extracts and stores associated cluster and workload information.
•	Determines active/inactive status based on observed generation.
•	Caches BindingPolicy data (including raw YAML) in Redis.
•	Includes periodic cache refresh every 30 seconds after an initial startup sync.
Fixes:
#399

✨ Feature: Watch BindingPolicy Changes and Sync with Redis

---

frontend/src/components/PluginManager.tsx

Change the Plugin Card's layout.
Fixes #1214
Before:
https://github.com/user-attachments/assets/fbf9844a-008f-44e6-83e8-94d327785578
After:
https://github.com/user-attachments/assets/7de9ccba-ce14-4faf-acaa-6e9aff2d33a2

refactor: change Plugin Card layout

---

.husky/pre-commit

Fixing pre commits of husky

---

docs/design-progress.md

- **Type Hierarchy Defined**:
- Introduced consistent typography system for documentation and UI.
- Defined font sizes, weights, and heading levels for visual hierarchy.
- Linked Figma resource for reference.
- Added Type Hierarchy Figma link to the resource list.
This update supports the design system’s visual consistency and improves documentation readability.

Added Type Hierarchy and Resources

---

frontend/src/components/PluginManager.tsx
frontend/src/components/plugin/FeedbackModel.tsx
frontend/src/locales/strings.en.json
frontend/src/locales/strings.es.json
frontend/src/locales/strings.fr.json
frontend/src/locales/strings.ja.json
frontend/src/plugins/PluginAPI.ts

This PR adds the plugin feedback form as a dialogue.
Fixes #1215 
https://github.com/user-attachments/assets/6116c392-2a9b-4267-842d-d1cd34c31274

feat: Add feedback dialogue on plugin card 

---

backend/go.mod
backend/telemetry/external_ops_metrics.go
backend/telemetry/http_metrics.go
backend/telemetry/k8s_client_metrics.go
backend/telemetry/kubestellar_metric.go
backend/telemetry/web_socket_metrics.go

initialises metric bases upon multiple functions

---

frontend/src/locales/strings.de.json
frontend/src/locales/strings.es.json
frontend/src/locales/strings.fr.json
frontend/src/locales/strings.it.json
frontend/src/locales/strings.ja.json
frontend/src/locales/strings.pt.json
frontend/src/locales/strings.zh-Hans.json
frontend/src/locales/strings.zh-Hant.json

This PR adds missing `"commandPalette"` translations (including the `"plugin"` command) for all supported languages and fixes JSON structure issues in locale files.
Fixes #1248

Add and Fix Command Palette Translations for All Locales

---

backend/test/utils/utils_test.go

feat: write test for `utils/utils.go`

---

backend/test/utils/installer_test.go

feat : Write Test for `utils/installer.go`

---

frontend/src/components/admin/DeleteUserModal.tsx
frontend/src/components/admin/UserFormModal.tsx
frontend/src/components/admin/UserList.tsx
frontend/src/components/admin/UserManagement.tsx
frontend/src/components/admin/UserService.ts
frontend/src/components/admin/UserTypes.ts
frontend/src/components/admin/index.ts
frontend/src/routes/routes-config.tsx

Create, Delete,Edit, Update in USER Table

Create, Delete,Edit, Update in USER Table

---

frontend/src/components/CommandPalette.tsx

FEAT: User Mangement in Command Palellet

FEAT: User Mangement in Command Palellet

---

frontend/src/locales/strings.de.json
frontend/src/locales/strings.en.json
frontend/src/locales/strings.es.json
frontend/src/locales/strings.fr.json
frontend/src/locales/strings.it.json
frontend/src/locales/strings.ja.json
frontend/src/locales/strings.pt.json
frontend/src/locales/strings.zh-Hans.json
frontend/src/locales/strings.zh-Hant.json

User management Strings for all Languages

User mananagement Strings for all LAng

---

backend/test/utils/jwt_test.go

Related: #1007
Test Passed Successfully

feat: Write test for `utils/jwt.go`

---

backend/test/utils/parser_test.go

feat: write test for `utils/parser.go`

---

backend/test/routes/wecs_test.go

Relates #1007
Test Run Successfully

feat: write test for `routes/wecs`

---

backend/test/routes/setup_test.go

Relates #1007 
Test Run Successfully

feat: write test for `routes/setup`

---

backend/test/routes/plugins_test.go

Relates #1007
Test Run Successfully

feat: write tests for `routes/plugin`

---

frontend/src/components/BindingPolicy/CreateBindingPolicyDialog.tsx
frontend/src/components/BindingPolicy/DeploymentConfirmationDialog.tsx
frontend/src/components/BindingPolicy/Dialogs/EditBindingPolicyDialog.tsx
frontend/src/components/BindingPolicy/Dialogs/PolicyDetailDialog.tsx
frontend/src/components/BindingPolicy/PolicyDragDropContainer.tsx
frontend/src/components/BindingPolicy/QuickPolicyDialog.tsx
frontend/src/components/DynamicDetailsPanel.tsx
frontend/src/components/WecsDetailsPanel.tsx
frontend/src/components/Workloads/UploadFileTab.tsx
frontend/src/components/Workloads/YamlTab.tsx

Revert "Complete Part 2: Vite chunking optimization and code splitting for heavy libraries"

---

backend/health/health.go
backend/redis/redis.go

Add a new Redis health check mechanism by replacing the previous HTTP-based check with a direct Redis client ping. It also includes the addition of a utility function `PingRedis` in the Redis package. These changes improve the accuracy and reliability of the Redis connectivity check.

Fixed Docker Compose Issue

---

backend/test/routes/metrics_test.go

Relates #1007
https://github.com/user-attachments/assets/23508cff-6cb1-47c0-ac3d-8bb76d9c6059
Test Runs Successfully

feat: write test for `routes/metrics`

---

frontend/src/components/PluginManager.tsx

Search feature in plugin manager was not working properly .
This PR ensure null checks and enchanes the search ability for plugins
Fixes #1232 
1.  ![image](https://github.com/user-attachments/assets/14347ffb-8b5d-444c-83c3-261385dd4ebd)
<hr/>
2 . ![image](https://github.com/user-attachments/assets/bc283f28-004a-42e5-bc86-9cd3878058f6)

PluginManager Search Bug - Rectified

---

frontend/src/locales/strings.de.json
frontend/src/locales/strings.es.json
frontend/src/locales/strings.fr.json
frontend/src/locales/strings.it.json
frontend/src/locales/strings.ja.json
frontend/src/locales/strings.pt.json
frontend/src/locales/strings.zh-Hans.json
frontend/src/locales/strings.zh-Hant.json

Add translations for "User Management" in Command Palette (All languages)
Fixes #1330

chore: add translation of User Management in Command Palette for all languages

---

backend/Makefile
backend/models/plugins.go
backend/postgresql/migrations/000003_plugin_feedback.down.sql
backend/postgresql/migrations/000003_plugin_feedback.up.sql

Make the migration files for Plugin Feedback
Fixes #1337

feat: create plugin_feedback table

---

backend/pkg/plugins/manager.go
backend/pkg/plugins/wasm_runtime.go

Implemented `wasm_runtime.go`

---

frontend/src/components/Wds_Topology/ZoomControls.tsx

fix typos of strings in `ZoomControl`

---

backend/test/api/handlers_test.go

Related #1141
https://github.com/user-attachments/assets/4aeb9e4e-1b91-40de-b45c-13981fbca978

Write test for `api/handlers.go`

---

backend/test/api/artifact_test.go

Related #1141
https://github.com/user-attachments/assets/2ff348dd-201b-4af3-8973-f786d325de17

Write Test for `api/artifact.go`

---

backend/test/api/installer_websocket_test.go

Write test for `api/installer_websocket.go`

---

frontend/src/components/Wds_Topology/NodeLabel.tsx

Fixes: #1357 
Place the icon and its label (dynamicText) stacked vertically and position them as the first element in the layout. Ensure they are clearly visible and do not interfere with the alignment of the object name. The object name (label) should be consistently aligned across all nodes, maintaining visual clarity and uniformity throughout the UI.

Fix: uniformity throughout the UI of NodeLabel

---

backend/test/installer/kubestellar_status_test.go

This PR introduces a test suite for verifying the behavior of the CheckKubeStellarStatus function and related utilities from the installer package
Fixes #1390 

Added test for /installer/kubestellar_status

---

backend/models/user.go
backend/routes/jwt.go
frontend/src/components/admin/UserManagement.tsx

1. Problem: The backend was calling auth.RemoveUser(username) instead of models.DeleteUser(username)
2. Fix: Updated DeleteUserHandler to use models.DeleteUser(username)
3. Additional: Enhanced the DeleteUser function in models to properly handle transactions and delete both user and permissions

Fix: Delete User Functionality

---

backend/models/user.go
backend/routes/jwt.go
frontend/src/components/admin/UserManagement.tsx
frontend/src/components/admin/UserService.ts

**Problem: The backend UpdateUserHandler didn't handle username updates, and the frontend wasn't sending the new username**
1. Added UpdateUserUsername function in models package to handle username updates with duplicate checking
2. Updated UpdateUserHandler to accept and process username updates
3. Updated frontend UserService.updateUser to include username in the request data
4. Updated frontend handleEditUser to send the new username and use it for permissions update

Fix: Edit Username and ISAdmin 

---

backend/test/wds/bp/handlers_test.go

Write test for `wds/bp/handlers`

---

backend/test/wds/controller_test.go

Write Test for `wds/controller.go`

---

backend/test/wds/deployment/status_test.go

write test for `deployement/status`

---

backend/test/log/log_test.go

This PR adds comprehensive test coverage for the `log/log.go` file - the structured logging utilities in the backend.
This file is fundamental to the application's observability and debugging capabilities. The added tests ensure high code coverage, include edge cases, and are designed to catch regressions effectively.
Fixes #1143
- All logging levels (Info, Error, Warn, Debug, Fatal)
- Structured logging with zap.Field parameters
- Performance testing for high-volume logging scenarios
- Concurrency testing for thread-safe logging operations
- Edge cases including empty messages, special characters, and various field types
- Proper handling of LogFatal (which calls os.Exit(1))
- Table-driven tests for comprehensive coverage
- Proper test isolation and cleanup
- Clear test naming and …

Add comprehensive tests for logging functions in log/log.go

---

backend/test/its/csr_watcher_test.go

Write test for `its-csr_command`

---

frontend/src/hooks/queries/useLogin.ts
frontend/src/lib/api.ts
frontend/src/lib/react-query/queryClient.ts
frontend/src/locales/strings.en.json

FIX : Multiple Toast Messages on Login Failure and Request failed with status code 401

---

backend/test/admin/auth_test.go

Write test for `admin/auth.go`

---

frontend/src/components/LanguageSwitcher.tsx

langauge menu selection on login page
Fixes https://github.com/kubestellar/ui/issues/1441

bug fix for LanguageSwitcher dropdown

---

backend/go.mod
backend/test/postgresql/Database/connection_test.go
backend/test/postgresql/config_test.go

test coverage for database
https://github.com/kubestellar/ui/issues/1439

Add PostgreSQL database test cases

---

frontend/src/components/MetricsDashboard.tsx

Fixes #1468 
[Screencast from 2025-07-12 21-36-37.webm](https://github.com/user-attachments/assets/81e80ec0-be39-4456-b8d4-a01cb237e3ed)

Fixes Typeerror in Metric Dashboard

---

frontend/src/components/PluginManager.tsx

This PR introductes notification toast for PluginManager.
Fixes #1476

fix: Add toast for notification replacing alert

---

README.md

Hi! Just noticed this while trying to install the UI, not sure if it is intentional.
N/A
NA
NA

Update README.md to correct git clone step

---

frontend/src/components/admin/UserFormModal.tsx

Fix Infinite loop issue in User Management Panel #1489
Fixes #1489 
fixed the infinite loop ! 
https://github.com/user-attachments/assets/94979f91-6cf0-4b48-b9df-02f51f45b434

Infinite loop issue in User Management Panel #1489

---

frontend/src/components/admin/UserFormModal.tsx
frontend/src/components/treeView/TreeViewFilters.tsx

Added preValidation to ensure , user can only click submit if the password matches the confirm password ! 
so that button doesn't remain stuck at processing.
Fixed [object object] issue 
#1497 
https://github.com/user-attachments/assets/c9b6e373-da5a-4284-a845-afe42270fd0c

Fix Edit User managment issue + [object object] #1497

---

frontend/src/components/login/KubeStellarLayout.tsx

Fixes #1543
Previous : 
https://github.com/user-attachments/assets/e5d6c046-2472-47e3-80fc-bcd89969f5fc
current: 
https://github.com/user-attachments/assets/84825fb7-8f3c-4102-b3c0-c122f74f0c4f

chore: improve the responsivness of the login page

---

frontend/src/components/Layout.tsx

chore: added tooltip to the main menu icon

---

frontend/src/locales/strings.en.json

Renamed "Resource Kind" to "Kind / Object" in Resource Explorer 

---

frontend/src/components/marketplace/CategoryFilter.tsx

Feat: Marketplace catogory

---

frontend/src/components/marketplace/PluginCard.tsx

Feat: Marketplace Cards

---

frontend/src/components/marketplace/PluginDetails.tsx

Feat : Marketplace Plugins Details

Feat : Marketplace Plugins Details

---

frontend/src/components/PluginManager.tsx
frontend/src/components/menu/useMenuData.ts
frontend/src/routes/routes-config.tsx

Feat: Marketplace In SideMenu and Plugin Maneger

Feat: Marketplace In SideMenu and Plugin Maneger

---

frontend/src/components/marketplace/CategoryFilter.tsx
frontend/src/pages/GalaxyMarketplace.tsx

Fix z-index layering issues where navbar dialogs were appearing below marketplace components. 
There were more issue, when we turn on the filter option same error happens so fixed that also.
Fixes #1580
https://github.com/user-attachments/assets/38a6ab4e-8e57-4668-8db2-422274a42589

fix: Nav bar dialogue

---

frontend/src/components/wds_topology/FlowCanvas.tsx

On refreshing staged workloads canvas will remain functional , no React Flow is shown on the top right corner after refresh ! 
Fixes #1552 
https://github.com/user-attachments/assets/f617477e-7df2-4197-bb98-8b233eb976bb

Fixed : On refreshing staged workloads canvas becomes non-functional

---

frontend/src/pages/Dashboard.tsx

Added total percentage for `CPU usage`, `Memory usage`, `Pod Health`.
Fixes #1618 
after changes:

fix: Update HealthIndicator and OptimizedProgressBar to display percentage as total percentage

---

docs/design-progress.md

Documented findings from exploring Next.js as a potential framework for the docs site.

Add Progress Update: Next.js Research for Documentation Framework

---

frontend/src/pages/Dashboard.tsx

Percentage thing which was not blur on dashboard when u open command palette
Fixes #1630 
After Fixing :

Inconsistent Ui homepage fixed 

---

.github/workflows/greeting.yml

Fixed broken links
Fixes #1664 

Fix broken links in greeting.yml

---

docs/design-progress.md

- Designed a **space-themed animated hero section** to reflect KubeStellar’s identity as a multi-cluster orchestration platform with cosmic scalability.

KubeStellar/docs Landing Page Design – Hero Section

---

frontend/src/components/ListViewComponent.tsx
frontend/src/components/ResourceFilters.tsx

This PR resolves the issue where pagination was not functioning properly in the **Deployed Workloads** list view. The pagination was always stuck on Page 1, page resets were triggered unnecessarily on navigation, and a JavaScript error occurred during initialization due to improper state management.
---
Fixes #1644
---
The total items count was being calculated from a stale `totalItems` state instead of the real-time filtered data, leading to:
- Incorrect total page calculations
- Pagination stuck on Page 1
- Buttons not functioning as expected
Even when users clicked "Next" or "Previous", the page reset to 1 because the filtering logic was running on every render or minor state change.
`resourceFilters` was being accessed before it was initialized, causing a runtime crash in some cases. …

Fix Pagination in Deployed Workloads List View

---

docs/design-progress.md

Designed an **interactive, visually engaging** "How It Works" section to explain KubeStellar’s architecture and workflow in simple, digestible steps.

KubeStellar/docs Landing Page Design – How It Works Section

---

docs/design-progress.md

**Have questions about KubeStellar? We're here to help!**
- Simple, approachable section encouraging user engagement.

KubeStellar/docs Landing Page Design – Get in Touch Section

---

frontend/src/components/wds_topology/ZoomControls.tsx
frontend/src/locales/strings.en.json

- **Modernized ZoomControls** using glassmorphism and Material-UI icons
- Fullscreen toggle added to TreeView and wecs
- Shared ZoomControls across TreeView and WECS for consistency

Glassmorphism ZoomControls & Fullscreen Support

---

frontend/src/locales/strings.en.json
frontend/src/locales/strings.hi.json
frontend/src/pages/InstallationPage.tsx

This PR tries to add Hindi translations. In HIndi UI, command palette is missing Hindi translations and the version instruction still shows in english
This PR aims to solve the issue : https://github.com/kubestellar/ui/issues/1726
Fixes #1726
Before : 
After:

frontend: InstallationPage: feat: Add translations for prerequisites check

---

README.md

fix `README` referencing older release version doc

---

README.md
frontend/src/components/CommandPalette.tsx
frontend/src/components/Header.tsx
frontend/src/components/LanguageSwitcher.tsx
frontend/src/components/MetricsDashboard.tsx
frontend/src/components/menu/Menu.tsx
frontend/src/components/menu/MenuItem.tsx
frontend/src/components/skeleton/FullScreenToggle.tsx
frontend/src/pages/Dashboard.tsx

This PR solves the error while running `npm run build` as discussed in issue #1761
After :

Fix `npm build` error for frontend

---

docs/design-progress.md

- Added **dropdown menus** to navbar buttons for improved navigation clarity.
- Each dropdown item paired with a **meaningful icon** for quick scanning.

Designed Navbar Button Dropdown with Meaningful Icons

---

backend/marketplace/storage.go

The unnecessary AppleDouble metadata file, which was created when archiving, caused the error when we upload the plugin.tar.gz file.
This PR resolves the issue by avoiding the file during the extraction process.
Fixes #1790

refactor: fix the plugin uploading problem

---

frontend/src/locales/strings.en.json
frontend/src/locales/strings.hi.json

- Added all missing keys from English to strings.hi.json with accurate Hindi translations and placed them in the correct nested sections.
- Verified there are no keys remaining that exist in English but not in Hindi.
- All missing English keys are now translated and added to strings.hi.json, and key Hindi phrasing/typos are corrected.
- Installation, header, clusters, topology, details panel, tree view, list view, command palette, menu, and resources sections updated.
- Fixed mixed-script and mislabels in menu items.
- Standardized “रीफ्रेश” phrasing in common places; can also flip the two “क्लस्टर्स सूची रिफ्रेश करें” instances on request.
- Fixed mixed-script and label issues in strings.hi.json:
- Changed menu.items.remoteClusters from “Remरिमोट क्लस्टर्स” to “रिमोट क्लस्टर्स”.
- …

Added all missing keys from English to `strings.hi.json`  & key Hindi phrasing/typos are corrected.

---

docs/design-progress.md

Added **Landing Page Design** link to Audit Resources (#7) in project documentation.

Added Landing page figma link

---

frontend/src/components/admin/UserManagement.tsx

This PR addresses styling inconsistencies in the RBAC dropdown component by:
1.   Aligning the dropdown appearance with our Language Switcher component for UI consistency
2.   Resolving overflow issues that caused dropdown cut-offs
3.   Improving hover/focus states for better accessibility
4.   Optimizing transition animations for smoother interactions
**Key Changes:**
1.   Refactored UserManagement.tsx dropdown implementation
2.   Removed conflicting overflow-hidden properties
3.   Updated z-index handling for proper layering
4.   Standardized padding and margins according to design system
5.   Styled Dropdown menu UI
Fixes  #1646 
**(Before)**
**(After)**
**Verified in:**
Desktop ZenBrowser/Chrome
Mobile viewports

Fixed: Styling Bug in CSS of dropdown in RBAC 

---

backend/pkg/plugins/store.go

fix: Change the plugin query to fix the plugin installation from the local

---

.github/workflows/assignment-helper.yml

feat: add assignment helper workflow to guide users to Prow commands

---

frontend/package-lock.json
frontend/src/components/treeView/TreeViewCanvas.tsx

* Adjusted the **card container's dimensions** to provide more **width** and reduce excessive **height** for better content visibility.
* Ensured the **entire card** is properly rendered and **not clipped/cut off** in the layout.
* Fixed **button positioning and visibility** issues within the card to ensure consistent and accessible design.
* Updated **responsive styles** (if applicable) to ensure proper rendering across screen sizes.
* **Before:** Card was clipped and had poor aspect ratio; button was not fully visible.
* **After:** Card displays fully with improved layout and button now clearly visible.

Unconsistent CSS in No workload found Card

---

README.md
frontend/src/components/login/KubeStellarLayout.tsx

Fixes #1760 
After: 
https://github.com/user-attachments/assets/efed886b-80ba-4431-afbf-4c7cb1d731bc

Fix responsiveness for `/login` page

---

backend/installer/Prerequisites.go

This PR improves the reliability and accuracy of the prerequisites check by refactoring command execution, version extraction, and architecture compatibility logic. It ensures better handling of missing binaries and version mismatches, and adds guards around Docker-based sysctl checks.
Fixes: #1721 
there was a bug in CheckCommand() so debugged it, and also in checking errors
This PR enhances accuracy of tool checks for Kubeflex, clusteradm, and others. It also improves robustness in CI/dev environments where some tools may emit warnings or fail partial commands.

refactor(installer): improve prerequisite checks and version extraction

---

frontend/src/pages/ResourceFilterPage.tsx

Fixed #1832 
[Screencast From 2025-08-15 00-02-35.webm](https://github.com/user-attachments/assets/9736eb5e-3035-4852-b910-2a6779bee2a4)

Fixed object type dropdown not searchable using keyboard

---

.github/workflows/report-on-vulnerabilities.yaml

Added one more steps for generating the sbom and uploading to artifact

feat(ci): add sbom generation and upload to artifact

---

backend/api/marketplace.go
backend/api/plugins.go
backend/models/plugins.go
backend/pkg/plugins/store.go
backend/postgresql/migrations/000005_add_isMarketplace_flag_to_plugin_details.down.sql
backend/postgresql/migrations/000005_add_isMarketplace_flag_to_plugin_details.up.sql

Fixes #1875
- Add new column **isMarketplacePlugin** to table plugin_details
- Create up and down migration file for it
- Allow plugin to be uploaded to markeplace even if it is already installed locally 
https://github.com/user-attachments/assets/886240ee-12a6-487f-a66a-27756a6d83b1

Fix: Manually Installed plugin can be uploaded to marketplace 

---

.gitignore

I was testing the ui-plugins 
I just cloned the ui-plugins in ks/ui so adding in .gitignore so by mistake i can't commit it

add ui-plugins in .gitignore

---

frontend/src/components/its/ImportCluster/ImportClusters.tsx
frontend/src/components/its/ImportCluster/KubeconfigImportTab.tsx

- Added drag-and-drop functionality to the KubeconfigImportTab for improved user experience.
- Introduced state management for drag events and updated UI styles based on drag state.
- Refactored file selection logic to handle both drag-and-drop and file input methods.
- Enhanced visual feedback during file upload process.
Fixes #1870 
https://github.com/user-attachments/assets/ca66d854-5346-4895-aa73-a255351e7427

feat: implement drag-and-drop file upload for kubeconfig in ImportCluster component

---

docs/design-progress.md

Designed a dedicated **Programs** page featuring card-based layouts.

KubeStellar/docs – Programs Page Design

---

docs/design-progress.md

Created a dedicated **GSoC program page** with structured content sections for clarity and accessibility:

 KubeStellar/docs – Google Summer of Code (GSoC) Page Design

---

backend/log/log.go
backend/redis/redis.go

enhance logging functionality by introducing dynamic log level configuration and updating log statements to debug level in Redis operations
Fixes #1844 

feat(logging): enhance logging functionality 

---

frontend/src/components/menu/MenuItem.tsx
frontend/src/components/menu/Tooltip.tsx

[Screencast From 2025-08-22 23-30-22.webm](https://github.com/user-attachments/assets/3bb19058-d4cb-42e5-bb32-da6d67ea193f)
Fixed #1735

Add hover tooltips for each icon in the collapsed vertical sidebar menu to improve usability.

---

frontend/src/components/ObjectFilters.tsx
frontend/src/components/ResourceCard.tsx
frontend/src/components/ResourceStats.tsx
frontend/src/locales/strings.en.json
frontend/src/locales/strings.hi.json
frontend/src/pages/ObjectFilterPage.tsx

Implemented i18n support for Object Explorer strings (English & Hindi)

---

docs/design-progress.md

Designed the IFoS program page with sections.

KubeStellar/docs – IFoS Page Design  

---

docs/design-progress.md

Designed the ESOC program page with sections.

KubeStellar/docs – ESOC Page Design

---

docs/design-progress.md

Added Figma link of contribute handbook and Program page.

Added Link in Resources

---

docs/design-progress.md

Developed a functional **landing page** on the web to test design and interactions beyond Figma.

KubeStellar/docs – Landing Page Web Design  

---

.env.example
backend/api/marketplace.go
backend/api/plugins.go
backend/main.go
backend/pkg/config/config.go
docker-compose.yml

This PR fixes Plugin file mount problem for docker.
Fixes #1907

fix: Plugin system now works with docker

---

frontend/src/components/menu/useMenuData.ts

introduce grafana icon 

---

frontend/src/components/wds_topology/ZoomControls.tsx

Fixes staged workload issue

---

CONTRIBUTING.md

Update Contribution.md for Playwright Setup

---

frontend/src/lib/api.ts

Fix Invalid Token toast on Login

---

.github/workflows/playwright.yml

Fixes #1959 
**This PR implements a GitHub Actions workflow to run Playwright tests automatically on all pull requests and pushes to protected branches.**
- Added GitHub Actions workflow (.github/workflows/playwright.yml)
- Triggers on PRs targeting main, development branches
- Triggers on pushes to main, development, and release branches
- Matrix strategy to test across multiple browsers and OSes
- Configured caching for faster execution
- Artifacts collection on test failure
- Uploads test videos, screenshots and traces when tests fail
- Helps with debugging test failures directly from CI
- Status checks requirement
- All Playwright tests must pass before merging
- Prevents merging of code that breaks end-to-end functionality

Setup CI/CD Pipeline with Playwright Tests

---

frontend/src/pages/InstallationPage.tsx

removed the deps of prerequisties from the useEffect dependancy array
used a mounted guard to avoid setting state on an unmounted component
Fixes #2000

refactor(prerequisites): improve state management and error handling in prerequisites check

---

.github/workflows/add-help-wanted.yml

Added `hacktoberfest` label for Hacktoberfest 2025 

feat: add '/hacktoberfest' command to label comments in GitHub workflow

---

frontend/src/pages/ObjectFilterPage.tsx

So this pr shows namespaces, when namespace is selected at Select Object/kind
Fixes #1830

feat: enhance resource handling with derived resource structure and optimized filtering to show NameSpaces
